"use client";

import { useState } from "react";

export interface PdfIssue {
  id?: string;
  label?: string;
  severity?: string;
  clauseReference?: string;
  message?: string;
  explanation?: string;
  recommendation?: string;
  matches?: string[];
}

export interface PdfDeadline {
  label?: string;
  value?: string;
  description?: string;
}

export interface PdfReportData {
  fileName?: string | null;
  analysisDate?: string;
  riskScore: number;
  summary?: string;
  issues: PdfIssue[];
  deadlines: PdfDeadline[];
}

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 15;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = 285;
const MAX_Y = 268;

const FOOTER_TEXT =
  "This report was generated by Huginn AI. It is not a substitute for professional legal advice. © Odens Eye Creative LLC";

function severityColor(severity?: string): [number, number, number] {
  if (severity === "critical") return [124, 58, 237];
  if (severity === "high") return [220, 38, 38];
  if (severity === "medium") return [217, 119, 6];
  if (severity === "missing") return [100, 116, 139];
  return [22, 163, 74]; // low
}

function severityLabel(severity?: string): string {
  if (severity === "critical") return "CRITICAL";
  if (severity === "high") return "HIGH";
  if (severity === "medium") return "MEDIUM";
  if (severity === "missing") return "MISSING";
  return "LOW";
}

function riskInfo(score: number): { label: string; color: [number, number, number] } {
  if (score <= 40) return { label: "HIGH RISK", color: [220, 38, 38] };
  if (score <= 70) return { label: "MODERATE RISK", color: [217, 119, 6] };
  return { label: "LOW RISK", color: [22, 163, 74] };
}

async function generatePdf(data: PdfReportData): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  let y = MARGIN + 5;
  let pageNum = 1;

  function addFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN, FOOTER_Y - 3, PAGE_W - MARGIN, FOOTER_Y - 3);
    doc.text(FOOTER_TEXT, PAGE_W / 2, FOOTER_Y, { align: "center" });
    doc.text(`Page ${pageNum}`, PAGE_W - MARGIN, FOOTER_Y, { align: "right" });
  }

  function newPage() {
    addFooter();
    doc.addPage();
    pageNum++;
    y = MARGIN + 5;
  }

  function checkPageBreak(neededHeight: number) {
    if (y + neededHeight > MAX_Y) newPage();
  }

  function sectionHeader(title: string) {
    checkPageBreak(12);
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(title.toUpperCase(), MARGIN, y);
    y += 2;
    doc.setDrawColor(203, 213, 225);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 5;
  }

  function wrappedText(
    text: string,
    x: number,
    maxW: number,
    size: number,
    color: [number, number, number],
    style: "normal" | "bold" = "normal"
  ): number {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxW) as string[];
    const lineH = size * 0.4;
    checkPageBreak(lines.length * lineH + 2);
    doc.text(lines, x, y);
    y += lines.length * lineH + 1;
    return lines.length * lineH + 1;
  }

  // ── HEADER ──────────────────────────────────────────────────────
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, PAGE_W, 22, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text("HUGINN AI", MARGIN, 13);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Contract Analysis Report", PAGE_W - MARGIN, 13, { align: "right" });

  y = 30;

  // File + date meta
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  const meta = [
    data.fileName ? `File: ${data.fileName}` : "File: Untitled Document",
    `Date: ${data.analysisDate ?? new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
  ];
  doc.text(meta.join("     "), MARGIN, y);
  y += 10;

  // ── HEALTH SCORE ─────────────────────────────────────────────────
  sectionHeader("Contract Health Score");

  const risk = riskInfo(data.riskScore);

  // Score number
  doc.setFont("helvetica", "bold");
  doc.setFontSize(42);
  doc.setTextColor(15, 23, 42);
  doc.text(String(data.riskScore), MARGIN, y + 10);

  // "/100" label
  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(148, 163, 184);
  const scoreW = doc.getTextWidth(String(data.riskScore)) + 2;
  doc.text("/ 100", MARGIN + scoreW + 2, y + 8);

  // Risk level pill
  const pillX = MARGIN + scoreW + 24;
  doc.setFillColor(...risk.color);
  doc.roundedRect(pillX, y + 1, 38, 7, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(risk.label, pillX + 19, y + 6, { align: "center" });

  y += 16;

  // Progress bar
  const barW = CONTENT_W;
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(MARGIN, y, barW, 4, 2, 2, "F");
  doc.setFillColor(...risk.color);
  doc.roundedRect(MARGIN, y, barW * (data.riskScore / 100), 4, 2, 2, "F");
  y += 10;

  // ── BEFORE YOU SIGN ──────────────────────────────────────────────
  sectionHeader("Before You Sign");

  if (data.summary) {
    wrappedText(data.summary, MARGIN, CONTENT_W, 10, [51, 65, 85]);
    y += 2;
  }

  // ── ISSUES ───────────────────────────────────────────────────────
  const regularIssues = data.issues.filter((i) => i.severity !== "missing");
  const missingIssues = data.issues.filter((i) => i.severity === "missing");

  if (regularIssues.length > 0) {
    sectionHeader(`Issues Found (${regularIssues.length})`);

    for (const issue of regularIssues) {
      checkPageBreak(30);

      // Severity pill
      const sc = severityColor(issue.severity);
      const sl = severityLabel(issue.severity);
      const pillW = doc.getStringUnitWidth(sl) * 8 * 0.352778 + 8;
      doc.setFillColor(sc[0], sc[1], sc[2], 0.12);
      // jsPDF doesn't support alpha in setFillColor directly — use light tints
      const tint: [number, number, number] = [
        Math.min(255, sc[0] + 180),
        Math.min(255, sc[1] + 180),
        Math.min(255, sc[2] + 180),
      ];
      doc.setFillColor(...tint);
      doc.roundedRect(MARGIN, y - 3, pillW, 6, 2, 2, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...sc);
      doc.text(sl, MARGIN + 4, y + 1);

      // Issue title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      const titleLines = doc.splitTextToSize(issue.label ?? "Issue", CONTENT_W - pillW - 6) as string[];
      doc.text(titleLines, MARGIN + pillW + 4, y + 1);
      y += Math.max(6, titleLines.length * 4) + 3;

      if (issue.clauseReference) {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(issue.clauseReference, MARGIN, y);
        y += 4;
      }

      const bodyText = issue.explanation || issue.message;
      if (bodyText) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text("WHAT THIS MEANS", MARGIN, y);
        y += 4;
        wrappedText(bodyText, MARGIN, CONTENT_W, 9, [51, 65, 85]);
      }

      if (issue.recommendation) {
        checkPageBreak(12);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text("WHAT TO DO", MARGIN, y);
        y += 4;
        wrappedText(issue.recommendation, MARGIN, CONTENT_W, 9, [51, 65, 85]);
      }

      // Divider between issues
      y += 2;
      doc.setDrawColor(241, 245, 249);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y);
      y += 4;
    }
  }

  // ── MISSING PROTECTIONS ──────────────────────────────────────────
  if (missingIssues.length > 0) {
    sectionHeader(`Missing Protections (${missingIssues.length})`);

    for (const mp of missingIssues) {
      checkPageBreak(20);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      const lines = doc.splitTextToSize(mp.label ?? "Missing clause", CONTENT_W) as string[];
      doc.text(lines, MARGIN, y);
      y += lines.length * 4 + 2;

      if (mp.explanation) {
        wrappedText(mp.explanation, MARGIN, CONTENT_W, 9, [51, 65, 85]);
      }
      if (mp.recommendation) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(100, 116, 139);
        doc.text("WHAT TO ASK FOR", MARGIN, y);
        y += 4;
        wrappedText(mp.recommendation, MARGIN, CONTENT_W, 9, [51, 65, 85]);
      }

      y += 2;
      doc.setDrawColor(241, 245, 249);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y);
      y += 4;
    }
  }

  // ── TIME-SENSITIVE CLAUSES ───────────────────────────────────────
  sectionHeader("Time-Sensitive Clauses");

  if (data.deadlines.length === 0) {
    wrappedText(
      "No auto-renewals or hard deadlines detected — nothing here requires immediate action on your calendar.",
      MARGIN,
      CONTENT_W,
      9,
      [51, 65, 85]
    );
  } else {
    for (const dl of data.deadlines) {
      checkPageBreak(18);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      const labelLines = doc.splitTextToSize(dl.label ?? "Deadline", CONTENT_W - 40) as string[];
      doc.text(labelLines, MARGIN, y);

      if (dl.value) {
        doc.setFillColor(255, 251, 235);
        const valW = doc.getStringUnitWidth(dl.value) * 9 * 0.352778 + 10;
        doc.roundedRect(PAGE_W - MARGIN - valW, y - 4, valW, 6, 2, 2, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(180, 83, 9);
        doc.text(dl.value, PAGE_W - MARGIN - valW / 2, y, { align: "center" });
      }

      y += labelLines.length * 4 + 2;

      if (dl.description) {
        wrappedText(dl.description, MARGIN, CONTENT_W, 9, [100, 116, 139]);
      }

      y += 2;
      doc.setDrawColor(241, 245, 249);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y);
      y += 4;
    }
  }

  // Footer on last page
  addFooter();

  const date = new Date().toISOString().slice(0, 10);
  doc.save(`huginn-report-${date}.pdf`);
}

interface Props {
  data: PdfReportData;
  className?: string;
}

export default function DownloadPdfButton({ data, className }: Props) {
  const [generating, setGenerating] = useState(false);

  async function handleClick() {
    setGenerating(true);
    try {
      await generatePdf(data);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <button
      type="button"
      onClick={handleClick}
      disabled={generating}
      className={
        className ??
        "inline-flex items-center rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white transition hover:opacity-80 disabled:opacity-50"
      }
    >
      {generating ? "Generating PDF..." : "Download PDF Report"}
    </button>
  );
}
