"use client";

import React, { ChangeEvent, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import {
  getAllProductConfigs,
  ProductConfig,
  ProductTemplate,
} from "./lib/productConfigs";
import AppHeader from "@/app/components/AppHeader";

type Severity = "low" | "medium" | "high";

interface DetectedIssue {
  id: string;
  label: string;
  severity: Severity;
  message: string;
  explanation?: string;
  recommendation: string;
  matchedClause?: string;
  matches?: string[];
}

interface DetectedDeadline {
  id: string;
  label: string;
  value: string;
}

interface AnalysisResult {
  product?: string;
  label?: string;
  description?: string;
  documentType?: string;
  riskScore?: number;
  riskLevel?: "low" | "medium" | "high";
  summary?: string;
  matchedKeywords?: string[];
  missingRequiredKeywords?: string[];
  forbiddenKeywordHits?: string[];
  issues?: DetectedIssue[];
  deadlines?: DetectedDeadline[];
  metadata?: {
    textLength?: number;
    issueCount?: number;
    deadlineCount?: number;
  };
}

const SAMPLE_CONTRACT_TEXT = `SERVICE AGREEMENT

This Service Agreement is entered into between Alpha Solutions LLC ("Provider") and BrightPath Marketing ("Client").

1. Services
Provider agrees to deliver digital marketing services including SEO, content creation, and ad management.

2. Payment Terms
Client agrees to pay $5,000 per month. Payment is due within a reasonable time after invoicing.

3. Term
This agreement begins on January 1, 2026 and continues for 12 months unless terminated earlier.

4. Termination
Either party may terminate this agreement at any time with written notice.

5. Liability
Provider is not liable for any damages arising from the use of services.

6. Confidentiality
Both parties agree to keep sensitive information confidential.

[INTENTIONALLY OMITTED]

7. Governing Law

8. Dispute Resolution
Any disputes will be handled in a mutually agreed manner.
`;

function titleCaseRiskLevel(value?: "low" | "medium" | "high") {
  if (!value) return "Unknown";
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function getRiskBadgeClass(riskLevel?: "low" | "medium" | "high") {
  if (riskLevel === "high") return "riskBadge riskHigh";
  if (riskLevel === "medium") return "riskBadge riskMedium";
  return "riskBadge riskLow";
}

function getSeverityClass(severity: Severity) {
  if (severity === "high") return "severityPill severityHigh";
  if (severity === "medium") return "severityPill severityMedium";
  return "severityPill severityLow";
}

function formatTemplateLabel(template: ProductTemplate): string {
  switch (template) {
    case "compliance_checker":
      return "Compliance Checker";
    case "deadline_monitor":
      return "Deadline Monitor";
    case "deadline_obligation_extractor":
      return "Deadline & Obligation Extractor";
    case "discrepancy_finder":
      return "Discrepancy Finder";
    default:
      return template;
  }
}

function toTitleCase(value?: string) {
  if (!value) return "Unknown";
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function getSummaryText(result: AnalysisResult | null): string {
  if (!result) return "No document analyzed yet.";
  return result.summary || "No summary available.";
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function highlightClauses(text: string, issues?: DetectedIssue[]) {
  let highlighted = escapeHtml(text);

  (issues || []).forEach((issue) => {
    if (!issue.matchedClause) return;
    const escapedClause = issue.matchedClause.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escapedClause, "gi");
    highlighted = highlighted.replace(
      regex,
      `<mark class="clause-highlight">${escapeHtml(issue.matchedClause)}</mark>`
    );
  });

  return highlighted.replace(/\n/g, "<br />");
}

function buildClientReadyRiskReport(params: {
  result: AnalysisResult;
  sourceText: string;
  fileName?: string | null;
  template: ProductTemplate;
}) {
  const { result } = params;
  const generatedAt = new Date().toLocaleString();

  const lines: string[] = [];

  const issues = result.issues ?? [];
  const orderedIssues = [
    ...issues.filter((issue) => issue.severity === "high"),
    ...issues.filter((issue) => issue.severity === "medium"),
    ...issues.filter((issue) => issue.severity === "low"),
  ];

  lines.push("HUGINN AI ANALYSIS REPORT");
  lines.push("Generated by Oden's Eye Creative");
  lines.push(`Date: ${generatedAt}`);
  lines.push("");
  lines.push("-".repeat(40));
  lines.push("");
  lines.push(`RISK LEVEL: ${(result.riskLevel || "low").toUpperCase()}`);
  lines.push(`RISK SCORE: ${result.riskScore ?? 0}/100`);
  lines.push("");
  lines.push("SUMMARY");
  lines.push(`${orderedIssues.length} issue${orderedIssues.length === 1 ? "" : "s"} detected:`);
  orderedIssues.forEach((issue) => {
    lines.push(`- ${issue.label} (${issue.severity.toUpperCase()})`);
  });
  lines.push("");

  lines.push("-".repeat(40));
  lines.push("");
  lines.push("ISSUES:");
  lines.push("");

  if (orderedIssues.length === 0) {
    lines.push("No issues detected.");
  } else {
    orderedIssues.forEach((issue, index) => {
      lines.push(`${index + 1}. ${issue.label}`);
      lines.push(`Severity: ${issue.severity.toUpperCase()}`);
      lines.push("Explanation:");
      lines.push(issue.explanation || issue.message || "No explanation provided.");
      lines.push("");
      lines.push("-".repeat(40));
      lines.push("");
    });
  }

  return lines.join("\n");
}

async function extractTextFromFile(file: File): Promise<string> {
  const lowerName = file.name.toLowerCase();

  if (lowerName.endsWith(".txt")) {
    return await file.text();
  }

  if (lowerName.endsWith(".pdf")) {
    const formData = new FormData();
    formData.append("file", file);

    const response = await fetch("/api/extract-pdf", {
      method: "POST",
      body: formData,
    });

    if (!response.ok) {
      throw new Error("Failed to extract text from PDF.");
    }

    const data = await response.json();
    return data.text || "";
  }

  if (lowerName.endsWith(".docx")) {
    const formData = new FormData();
    formData.append("file", file);

    const response = await fetch("/api/extract-docx", {
      method: "POST",
      body: formData,
    });

    if (!response.ok) {
      throw new Error("Failed to extract text from DOCX.");
    }

    const data = await response.json();
    return data.text || "";
  }

  throw new Error("Unsupported file type. Please upload PDF, DOCX, or TXT.");
}

export default function Page() {
  const { data: session } = useSession();
  const productConfigs = useMemo<ProductConfig[]>(() => getAllProductConfigs(), []);
  const [template, setTemplate] =
    useState<ProductTemplate>("compliance_checker");
  const [documentText, setDocumentText] = useState("");
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isExtracting, setIsExtracting] = useState(false);
  const [error, setError] = useState("");
  const [warning, setWarning] = useState("");
  const [fileName, setFileName] = useState<string | null>(null);
  const [processedFileType, setProcessedFileType] = useState<string | null>(null);
  const [extractionStatus, setExtractionStatus] = useState<"Full" | "Partial" | null>(null);
  const [resultTimestamp, setResultTimestamp] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const templateMeta = useMemo<ProductConfig | undefined>(() => {
    return productConfigs.find((config: ProductConfig) => config.id === template);
  }, [productConfigs, template]);

  const selectedTemplateLabel = templateMeta?.label || "Analysis Results";

  const hasAnalysisResult =
    !!result &&
    typeof result.riskScore === "number" &&
    typeof result.label === "string" &&
    result.label.length > 0;

  const primaryCtaHref = session ? "/dashboard" : "/signup";

  async function runAnalysis(
    text: string,
    selectedTemplate: ProductTemplate,
    uploadedFile?: File | null
  ) {
    const trimmed = text.trim();

    if (!trimmed) {
      setError("Please paste document text or upload a PDF, DOCX, or TXT file.");
      setResult(null);
      return;
    }

    try {
      setIsAnalyzing(true);
      setError("");
      if (!uploadedFile) {
        setWarning("");
      }

      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({
          text: trimmed,
          template: selectedTemplate,
          config: {},
          fileName: uploadedFile?.name || fileName || null,
        }),
      });

      if (response.status === 401) {
        setError("Please log in to analyze a contract.");
        setResult(null);
        return;
      }

      if (!response.ok) {
        let message = "Analysis failed. Please try again.";

        try {
          const text = await response.text();
          if (text) {
            message = text;
          }
        } catch {}

        setError(message);
        setResult(null);
        return;
      }

      const data = await response.json();

      const nextResult =
        data &&
        typeof data === "object" &&
        typeof data.riskScore === "number"
          ? (data as AnalysisResult)
          : null;

      if (!nextResult) {
        throw new Error("Analysis returned an unexpected response.");
      }

      setResult(nextResult);
      setResultTimestamp(new Date().toLocaleString());
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : "Something went wrong during analysis.";
      setError(message);
      setResult(null);
    } finally {
      setIsAnalyzing(false);
    }
  }

  async function handleFileSelected(file: File) {
    setError("");
    setWarning("");
    setIsExtracting(true);

    try {
      const extractedText = await extractTextFromFile(file);

      const lowerName = file.name.toLowerCase();
      if (lowerName.endsWith(".pdf")) {
        setProcessedFileType("PDF");
      } else if (lowerName.endsWith(".docx")) {
        setProcessedFileType("DOCX");
      } else {
        setProcessedFileType("TXT");
      }

      if (extractedText.length < 500) {
        setWarning(
          "Warning:\nWe could not fully extract text from this file.\nResults may be incomplete."
        );
        setExtractionStatus("Partial");
      } else {
        setExtractionStatus("Full");
      }

      setDocumentText(extractedText);
      setFileName(file.name);

      await runAnalysis(extractedText, template, file);
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : "Failed to process the uploaded file.";
      setError(message);
    } finally {
      setIsExtracting(false);
    }
  }

  async function handleInputFileChange(
    event: ChangeEvent<HTMLInputElement>
  ) {
    const file = event.target.files?.[0];
    if (!file) return;

    await handleFileSelected(file);

    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  }

  async function handleTemplateChange(nextTemplate: ProductTemplate) {
    setTemplate(nextTemplate);
    setError("");

    if (documentText.trim()) {
      await runAnalysis(documentText, nextTemplate);
    }
  }

  function loadSampleContract() {
    setDocumentText(SAMPLE_CONTRACT_TEXT);
    setFileName(null);
    setError("");
    setResult(null);
    setWarning("");
    setProcessedFileType(null);
    setExtractionStatus(null);

    void runAnalysis(SAMPLE_CONTRACT_TEXT, template);

    document.getElementById("analyzer")?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  }

  function handleDownloadReport() {
    if (!result) return;

    const report = buildClientReadyRiskReport({
      result,
      sourceText: documentText,
      fileName,
      template,
    });

    const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    const safeTemplate = template.replace(/_/g, "-");

    anchor.href = url;
    anchor.download = `huginn-${safeTemplate}-report.txt`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <>
      <AppHeader />

      <main className="pageShell">
        <section className="w-full py-28 px-6 text-center bg-gradient-to-b from-white to-gray-100">
          <h1 className="text-4xl font-bold mb-6">
            Know What You're Signing Before You Sign It
          </h1>

          <p className="text-sm tracking-widest text-blue-600 mb-4">
            OBSERVE • ANALYZE • PROTECT
          </p>

          <p className="text-lg text-gray-600 max-w-2xl mx-auto mb-8">
            Huginn AI reads your contracts and flags what could hurt your business — in plain English, in seconds. No lawyer needed.
          </p>

          <div className="flex justify-center gap-4">
            <Link
              href={primaryCtaHref}
              className="inline-flex items-center justify-center rounded-2xl bg-blue-600 px-8 py-4 text-xl font-semibold text-white hover:bg-blue-700"
            >
              Get Started Free
            </Link>

            <button
              onClick={loadSampleContract}
              className="border border-gray-300 px-6 py-3 rounded-lg hover:bg-gray-100"
            >
              Try Sample Contract
            </button>
          </div>

        </section>

        <section className="py-16 px-6 bg-gray-50">
          <h2 className="text-3xl font-bold text-center mb-12">
            How Huginn AI Analyzes Contracts
          </h2>

          <div className="grid md:grid-cols-3 gap-10 max-w-5xl mx-auto text-center">
            <div>
              <div className="text-3xl font-bold text-blue-600 mb-4">1</div>
              <h3 className="font-semibold mb-2">Upload Contract</h3>
              <p className="text-gray-600">
                Upload a PDF, DOCX, or paste contract text into Huginn.
              </p>
            </div>

            <div>
              <div className="text-3xl font-bold text-blue-600 mb-4">2</div>
              <h3 className="font-semibold mb-2">Analyze Risk</h3>
              <p className="text-gray-600">
                Huginn reads every clause and flags what could cost you — risky terms, missing protections, hidden deadlines.
              </p>
            </div>

            <div>
              <div className="text-3xl font-bold text-blue-600 mb-4">3</div>
              <h3 className="font-semibold mb-2">Get Risk Report</h3>
              <p className="text-gray-600">
                Receive a clear report with risks, deadlines, and recommendations.
              </p>
            </div>
          </div>
        </section>

        <section className="py-16 px-6">
          <h2 className="text-2xl font-bold text-center mb-12">
            Tools Included
          </h2>

          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            <div className="border rounded-lg p-6">
              <h3 className="font-semibold mb-2">Contract Risk Analyzer</h3>
              <p className="text-gray-600 text-sm">
                Detect clauses that expose your business to legal or financial risk.
              </p>
            </div>

            <div className="border rounded-lg p-6">
              <h3 className="font-semibold mb-2">Compliance Checker</h3>
              <p className="text-gray-600 text-sm">
                Identify missing legal protections and compliance issues.
              </p>
            </div>

            <div className="border rounded-lg p-6">
              <h3 className="font-semibold mb-2">Deadline Extractor</h3>
              <p className="text-gray-600 text-sm">
                Automatically detect renewal dates, notice periods, and obligations.
              </p>
            </div>
          </div>
        </section>

        <section id="features" className="py-16 px-6 bg-gray-50">
          <h2 className="text-2xl font-bold text-center mb-12">
            Stop Signing Contracts Blind
          </h2>

          <div className="grid md:grid-cols-4 gap-8 max-w-6xl mx-auto text-center">
            <div>
              <h3 className="font-semibold mb-2">Catch the Clauses That Cost You</h3>
              <p className="text-gray-600">
                Auto-renewals, uncapped liability, one-sided termination — Huginn finds the terms most people miss until it's too late.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">Know What's Missing</h3>
              <p className="text-gray-600">
                Missing liability caps, no dispute process, undefined jurisdiction — gaps in a contract can hurt as much as bad clauses.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">Never Miss a Deadline</h3>
              <p className="text-gray-600">
                Renewal windows, notice periods, obligation dates — pulled out automatically so nothing sneaks up on you.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">Know What to Do Next</h3>
              <p className="text-gray-600">
                Every flagged issue comes with a plain-English recommendation so you know exactly what to ask for before you sign.
              </p>
            </div>
          </div>
        </section>

        <section id="pricing" className="py-20 px-6 text-center">
          <h2 className="text-2xl font-bold mb-10">Simple Pricing</h2>

          <div className="flex flex-col md:flex-row gap-6 max-w-3xl mx-auto justify-center items-stretch">
            <div className="flex-1 border rounded-xl p-8 shadow-sm">
              <h3 className="text-xl font-semibold mb-2">Free</h3>
              <p className="text-3xl font-bold mb-6">$0<span className="text-lg">/month</span></p>

              <ul className="text-gray-600 mb-8 space-y-2 text-left">
                <li>3 contract analyses per month</li>
                <li>Risk scoring and issue flagging</li>
                <li>Plain-English explanations</li>
                <li>No credit card required</li>
              </ul>

              <a
                href="/signup"
                className="block w-full border border-blue-600 text-blue-600 px-6 py-3 rounded-lg hover:bg-blue-50"
              >
                Get Started Free
              </a>
            </div>

            <div className="flex-1 border rounded-xl p-8 shadow-sm relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-blue-600 text-white text-xs font-semibold px-3 py-1 rounded-full">
                Most Popular
              </div>
              <h3 className="text-xl font-semibold mb-2">Pro</h3>
              <p className="text-3xl font-bold mb-6">$29<span className="text-lg">/month</span></p>

              <ul className="text-gray-600 mb-8 space-y-2 text-left">
                <li>Unlimited contract analyses</li>
                <li>Risk scoring with High / Medium / Low severity</li>
                <li>Clause-level recommendations</li>
                <li>Multi-file upload support</li>
                <li>Priority support</li>
              </ul>

              <a
                href="/dashboard"
                className="block w-full bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700"
              >
                Get Started
              </a>
            </div>
          </div>
        </section>

        <section id="analyzer" className="mt-24">
          <div className="text-center mb-10">
            <h2 className="text-2xl font-semibold text-gray-900">
              Try It Now — No Account Needed
            </h2>

            <p className="mt-3 text-gray-600">
              Upload a contract or paste text and see your risk report in seconds.
            </p>
          </div>

          <div className="mainGrid">
          <section className="card leftCard">
            <div className="uploadPanel">
              <button
                type="button"
                className="uploadButton"
                onClick={() => fileInputRef.current?.click()}
                disabled={isExtracting || isAnalyzing}
              >
                {isExtracting
                  ? "Extracting text..."
                  : isAnalyzing
                    ? "Analyzing contract..."
                    : "Analyze My Contract"}
              </button>

              <p className="uploadSubtitle">
                Upload PDF, DOCX, or TXT. Analysis starts automatically after
                upload.
              </p>
              <p className="uploadSubtitle">Secure file processing.</p>
              <p className="uploadSubtitle">
                Your documents are not stored permanently beyond operational retention needs.
              </p>
            </div>

            <label htmlFor="fileUpload" className="srOnly">
              Upload contract file
            </label>

            <input
              ref={fileInputRef}
              id="fileUpload"
              type="file"
              accept=".pdf,.docx,.txt"
              className="hiddenInput"
              onChange={handleInputFileChange}
              aria-label="Upload PDF, DOCX, or TXT file"
              title="Upload PDF, DOCX, or TXT file"
              tabIndex={-1}
            />

            <label className="fieldLabel" htmlFor="documentText">
              Document Text
            </label>

            <textarea
              id="documentText"
              className="textArea"
              placeholder="Paste document text here or upload a PDF, DOCX, or TXT file."
              value={documentText}
              onChange={(e) => setDocumentText(e.target.value)}
            />

            <p className="fieldLabel documentPreviewLabel">Document Preview</p>
            <div
              className="documentViewer"
              dangerouslySetInnerHTML={{
                __html: highlightClauses(documentText || "", result?.issues),
              }}
            />

            <div className="textMetaRow">
              <span>{documentText.length} characters</span>
              <span>{fileName ? `Loaded file: ${fileName}` : "No file loaded"}</span>
            </div>

            {error ? <div className="errorBox">{error}</div> : null}
          </section>

          <section className="card rightCard">
            {isAnalyzing ? (
              <div className="analysisLoading">
                <p className="analysisLoadingTitle">Analyzing contract...</p>
                <p className="analysisLoadingText">
                  Reviewing clauses, risks, and deadlines.
                </p>
              </div>
            ) : !hasAnalysisResult ? (
              <div className="emptyState">
                <h2 className="resultTitle">Results</h2>
                <p className="emptyText">Upload a contract to begin analysis.</p>
                <p className="emptyText">Supported files: PDF, DOCX, TXT</p>
              </div>
            ) : (
              <>
                {warning ? <div className="warningBox">{warning}</div> : null}

                {processedFileType && extractionStatus ? (
                  <p className="toolDescription">
                    File processed: {processedFileType}<br />
                    Text extraction: {extractionStatus}
                  </p>
                ) : null}

                {resultTimestamp ? (
                  <p className="toolDescription">Analyzed at: {resultTimestamp}</p>
                ) : null}

                <h2 className="toolTitle">{result?.label || selectedTemplateLabel}</h2>
                <p className="toolDescription">{result?.description || ""}</p>

                <div className={getRiskBadgeClass(result!.riskLevel)}>
                  {result!.riskLevel === "high" ? "🔴 " : result!.riskLevel === "medium" ? "🟠 " : "🟢 "}
                  {titleCaseRiskLevel(result!.riskLevel)} Risk
                </div>

                <div className="statGrid">
                  <div className="statCard">
                    <p className="statLabel">Risk Score</p>
                    <div className="flex items-end gap-2">
                      <span className="text-5xl font-black text-slate-900">
                        {result!.riskScore ?? 0}
                      </span>
                      <span className="text-xl font-semibold text-blue-600">/100</span>
                    </div>
                  </div>

                  <div className="statCard statCardDocumentType">
                    <p className="statLabel">Document Type</p>
                    <p className="text-xl font-semibold leading-tight text-slate-900 whitespace-normal">
                      {(result?.documentType || "Unknown")
                        .replace(/_/g, " ")
                        .replace(/\b\w/g, (char) => char.toUpperCase())}
                    </p>
                  </div>
                </div>

                <div className="summaryCard">
                  <p className="summaryLabel">Summary</p>
                  <p className="summaryText">{getSummaryText(result)}</p>
                </div>

                <button
                  type="button"
                  className="secondaryButton downloadButton"
                  onClick={handleDownloadReport}
                >
                  Download Risk Report
                </button>

                <div className="sectionCard">
                  <h3 className="sectionTitle">Issues Found</h3>

                  {(result!.issues?.length ?? 0) === 0 ? (
                    <div className="emptyPanel">No issues found.</div>
                  ) : (
                    <div className="stack">
                      {(result!.issues ?? []).map((issue) => (
                        <div key={issue.id} className="issueCard">
                          <div className="issueHeader">
                            <h4 className="issueTitle">{issue.label}</h4>
                            <span className={getSeverityClass(issue.severity)}>
                              {issue.severity.toUpperCase()}
                            </span>
                          </div>

                          <p className="issueMessage">{issue.message}</p>

                          <p className="issueRecommendationTitle">What this means</p>
                          <p className="issueRecommendationText">
                            {issue.explanation || issue.message}
                          </p>

                          <p className="issueRecommendationTitle">Recommendation</p>
                          <p className="issueRecommendationText">{issue.recommendation}</p>

                          {issue.matchedClause ? (
                            <div className="matchBlock">
                              <p className="matchesLabel">Matched Clause</p>
                              <p className="matchText">{issue.matchedClause}</p>
                            </div>
                          ) : null}
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="sectionCard">
                  <h3 className="sectionTitle">Deadlines</h3>

                  {(result!.deadlines?.length ?? 0) === 0 ? (
                    <div className="emptyPanel">No deadlines found.</div>
                  ) : (
                    <div className="stack">
                      {(result!.deadlines ?? []).map((deadline, index) => (
                        <div
                          key={`${deadline.id}-${index}`}
                          className="deadlineCard"
                        >
                          <p className="deadlineLabel">{deadline.label}</p>
                          <p className="deadlineValue">{deadline.value}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </>
            )}
          </section>
          </div>
        </section>

      </main>

      <style jsx>{`
        .pageShell {
          min-height: 100vh;
          padding: 36px 20px 52px;
          background:
            radial-gradient(
              circle at top left,
              rgba(37, 99, 235, 0.08),
              transparent 28%
            ),
            linear-gradient(180deg, #f7f9fc 0%, #eef2f7 100%);
          color: #0f172a;
          font-family: Inter, ui-sans-serif, system-ui, -apple-system,
            BlinkMacSystemFont, "Segoe UI", sans-serif;
        }

        .heroBlock {
          max-width: 1200px;
          margin: 0 auto 34px;
        }

        .brandEyebrow {
          margin: 0 0 14px;
          font-size: 13px;
          font-weight: 700;
          letter-spacing: 0.16em;
          text-transform: uppercase;
          color: #94a3b8;
        }

        .heroBrand {
          margin: 0;
          font-size: clamp(56px, 10vw, 104px);
          line-height: 0.92;
          font-weight: 900;
          letter-spacing: 0.06em;
          text-transform: uppercase;
          background: linear-gradient(90deg, #2563eb, #1d4ed8, #0ea5e9);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          text-shadow: 0 8px 30px rgba(37, 99, 235, 0.25);
        }

        .heroTagline {
          margin: 24px 0 0;
          font-size: 15px;
          font-weight: 700;
          letter-spacing: 0.28em;
          text-transform: uppercase;
          color: #64748b;
        }

        .heroProduct {
          margin: 18px 0 0;
          font-size: clamp(28px, 4vw, 46px);
          line-height: 0.98;
          font-weight: 800;
          letter-spacing: -0.04em;
          color: #0f172a;
        }

        .heroSubtitle {
          max-width: 1120px;
          margin: 22px 0 0;
          font-size: clamp(20px, 2vw, 24px);
          line-height: 1.65;
          color: #64748b;
        }

        .mainGrid {
          max-width: 1200px;
          margin: 0 auto;
          display: grid;
          grid-template-columns: 1.05fr 0.95fr;
          gap: 24px;
          align-items: start;
        }

        .card {
          background: rgba(255, 255, 255, 0.88);
          backdrop-filter: blur(10px);
          border: 1px solid rgba(203, 213, 225, 0.9);
          border-radius: 30px;
          padding: 32px;
          box-shadow:
            0 12px 36px rgba(15, 23, 42, 0.05),
            0 2px 6px rgba(15, 23, 42, 0.03);
        }

        .fieldLabel {
          display: block;
          margin-bottom: 14px;
          font-size: 18px;
          font-weight: 800;
          color: #1e293b;
        }

        .selectInput {
          width: 100%;
          border: 1px solid #cad5e2;
          border-radius: 20px;
          padding: 18px 20px;
          font-size: 17px;
          background: #ffffff;
          color: #0f172a;
          outline: none;
        }

        .templateDescription {
          margin: 18px 4px 28px;
          color: #64748b;
          font-size: 16px;
          line-height: 1.6;
        }

        .uploadPanel {
          border: 1px solid #d9e2ec;
          border-radius: 24px;
          padding: 26px;
          margin-bottom: 28px;
          background: linear-gradient(180deg, #f8fbff 0%, #f3f7fc 100%);
        }

        .uploadButton {
          border-radius: 18px;
          padding: 18px 24px;
          font-size: 17px;
          font-weight: 800;
          cursor: pointer;
          transition:
            transform 0.15s ease,
            opacity 0.15s ease,
            border-color 0.15s ease,
            box-shadow 0.15s ease;
          border: 1px solid #cad5e2;
          background: #ffffff;
          color: #334155;
        }

        .uploadButton:hover {
          transform: translateY(-1px);
        }

        .uploadButton:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none;
          box-shadow: none;
        }

        .uploadSubtitle {
          margin: 14px 0 0;
          color: #64748b;
          font-size: 16px;
          line-height: 1.55;
        }

        .hiddenInput {
          display: none;
        }

        .srOnly {
          position: absolute;
          width: 1px;
          height: 1px;
          padding: 0;
          margin: -1px;
          overflow: hidden;
          clip: rect(0, 0, 0, 0);
          white-space: nowrap;
          border: 0;
        }

        .textArea {
          width: 100%;
          min-height: 180px;
          resize: vertical;
          border: 1px solid #cad5e2;
          border-radius: 22px;
          padding: 20px;
          font-size: 16px;
          line-height: 1.6;
          color: #0f172a;
          background: #ffffff;
          outline: none;
          box-sizing: border-box;
        }

        .documentPreviewLabel {
          margin-top: 16px;
        }

        .documentViewer {
          margin-top: 14px;
          min-height: 140px;
          border: 1px solid #d9e2ec;
          border-radius: 16px;
          background: #fff;
          padding: 14px;
          white-space: pre-wrap;
          font-size: 15px;
          line-height: 1.6;
          color: #1f2937;
          overflow-wrap: anywhere;
          word-break: break-word;
          max-height: 240px;
          overflow: auto;
          border-radius: 16px;
          background: #fafbff;
        }

        .clause-highlight {
          background: #fde68a;
          padding: 2px 4px;
          border-radius: 4px;
        }

        .textMetaRow {
          margin-top: 14px;
          display: flex;
          justify-content: space-between;
          gap: 16px;
          flex-wrap: wrap;
          font-size: 14px;
          color: #64748b;
        }

        .errorBox {
          margin-top: 18px;
          padding: 14px 16px;
          border-radius: 16px;
          background: #fef2f2;
          border: 1px solid #fecaca;
          color: #991b1b;
          font-size: 15px;
          font-weight: 700;
        }

        .secondaryButton {
          border-radius: 18px;
          padding: 18px 24px;
          font-size: 17px;
          font-weight: 800;
          cursor: pointer;
          transition:
            transform 0.15s ease,
            opacity 0.15s ease,
            border-color 0.15s ease,
            box-shadow 0.15s ease;
          border: 1px solid #cad5e2;
          background: #ffffff;
          color: #334155;
        }

        .secondaryButton:hover {
          transform: translateY(-1px);
        }

        .secondaryButton:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none;
          box-shadow: none;
        }

        .emptyState {
          min-height: 180px;
        }

        .analysisLoading {
          border: 1px solid #c7d2fe;
          border-radius: 24px;
          padding: 24px;
          background: linear-gradient(180deg, #eef2ff 0%, #e0e7ff 100%);
        }

        .warningBox {
          border: 1px solid #fde68a;
          border-radius: 16px;
          padding: 12px 14px;
          background: #fefce8;
          color: #854d0e;
          font-size: 14px;
          line-height: 1.5;
          white-space: pre-line;
          margin-bottom: 16px;
        }

        .analysisLoadingTitle {
          margin: 0 0 8px;
          font-size: 22px;
          font-weight: 800;
          color: #312e81;
        }

        .analysisLoadingText {
          margin: 0;
          font-size: 16px;
          line-height: 1.6;
          color: #4338ca;
        }

        .resultTitle,
        .toolTitle {
          margin: 0 0 14px;
          font-size: clamp(28px, 3vw, 40px);
          line-height: 1.05;
          font-weight: 800;
          letter-spacing: -0.03em;
          color: #0f172a;
        }

        .toolDescription,
        .emptyText {
          margin: 0 0 24px;
          color: #64748b;
          font-size: 18px;
          line-height: 1.6;
        }

        .riskBadge {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 12px 18px;
          border-radius: 999px;
          font-size: 14px;
          font-weight: 800;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          margin-bottom: 24px;
          border: 1px solid transparent;
        }

        .riskLow {
          background: #eaf8ef;
          border-color: #b7e4c2;
          color: #0f8a4b;
        }

        .riskMedium {
          background: #fff7e8;
          border-color: #f3d39c;
          color: #c46b00;
        }

        .riskHigh {
          background: #fef2f2;
          border-color: #fecaca;
          color: #b91c1c;
        }

        .statGrid {
          display: grid;
          grid-template-columns: 1fr 2fr;
          gap: 20px;
          margin-bottom: 24px;
        }

        .statCard {
          display: flex;
          flex-direction: column;
          justify-content: center;
          border: 1px solid #d9e2ec;
          border-radius: 22px;
          padding: 22px;
          background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);
          min-width: 0;
        }

        .statCardDocumentType {
          min-width: 260px;
        }

        .statLabel {
          margin: 0 0 12px;
          font-size: 13px;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 0.12em;
          color: #64748b;
        }

        .statValue {
          margin: 0;
          font-size: clamp(22px, 3vw, 34px);
          line-height: 1.1;
          font-weight: 800;
          color: #0f172a;
          word-break: break-word;
        }

        .summaryCard,
        .sectionCard {
          border: 1px solid #d9e2ec;
          border-radius: 24px;
          padding: 24px;
          background: linear-gradient(180deg, #f8fafc 0%, #f4f8fc 100%);
          margin-top: 24px;
        }

        .summaryLabel {
          margin: 0 0 12px;
          font-size: 13px;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 0.12em;
          color: #64748b;
        }

        .summaryText {
          margin: 0;
          color: #334155;
          font-size: 18px;
          line-height: 1.7;
          white-space: pre-line;
        }

        .downloadButton {
          margin-top: 24px;
        }

        .sectionTitle {
          margin: 0 0 22px;
          font-size: 22px;
          line-height: 1.15;
          font-weight: 800;
          color: #0f172a;
        }

        .stack {
          display: grid;
          gap: 18px;
        }

        .issueCard,
        .deadlineCard {
          background: #ffffff;
          border: 1px solid #d9e2ec;
          border-radius: 22px;
          padding: 22px;
        }

        .issueHeader {
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          gap: 16px;
          margin-bottom: 14px;
        }

        .issueTitle {
          margin: 0;
          font-size: 18px;
          font-weight: 800;
          line-height: 1.3;
          color: #0f172a;
        }

        .severityPill {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 10px 14px;
          border-radius: 999px;
          font-size: 13px;
          font-weight: 800;
          letter-spacing: 0.08em;
          border: 1px solid transparent;
          white-space: nowrap;
        }

        .severityLow {
          background: #f0fdf4;
          border-color: #bbf7d0;
          color: #16a34a;
        }

        .severityMedium {
          background: #fefce8;
          border-color: #fde68a;
          color: #ca8a04;
        }

        .severityHigh {
          background: #fef2f2;
          border-color: #fecaca;
          color: #dc2626;
        }

        .issueMessage,
        .issueRecommendationText,
        .deadlineLabel,
        .deadlineValue {
          margin: 0;
          color: #334155;
          font-size: 17px;
          line-height: 1.7;
        }

        .issueRecommendationTitle {
          margin: 0;
          margin-top: 14px;
          font-size: 13px;
          font-weight: 800;
          color: #334155;
          text-transform: uppercase;
          letter-spacing: 0.08em;
        }

        .issueRecommendationText {
          margin: 6px 0 0;
          color: #334155;
          font-size: 17px;
          line-height: 1.7;
        }

        .matchBlock {
          margin-top: 18px;
          padding: 14px;
          border-radius: 16px;
          background: #f1f5f9;
          border: 1px solid #e2e8f0;
        }

        .matchesLabel {
          margin: 0 0 10px;
          font-size: 13px;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 0.12em;
          color: #64748b;
        }

        .matchText {
          margin: 0;
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
            "Liberation Mono", "Courier New", monospace;
          font-size: 14px;
          line-height: 1.7;
          color: #334155;
          white-space: pre-wrap;
          word-break: break-word;
        }

        .matchChipRow {
          display: flex;
          flex-wrap: wrap;
          gap: 10px;
          margin-top: 12px;
        }

        .matchChip {
          display: inline-flex;
          align-items: center;
          padding: 10px 14px;
          border-radius: 999px;
          background: #eef2f7;
          border: 1px solid #d9e2ec;
          color: #475569;
          font-size: 15px;
        }

        .deadlineLabel {
          font-weight: 800;
          color: #0f172a;
          margin-bottom: 8px;
        }

        .emptyPanel {
          border: 1px dashed #d1d9e6;
          border-radius: 20px;
          padding: 20px;
          background: #ffffff;
          color: #64748b;
          font-size: 17px;
        }

        @media (max-width: 1080px) {
          .mainGrid {
            grid-template-columns: 1fr;
          }
        }

        @media (max-width: 720px) {
          .pageShell {
            padding: 24px 16px 40px;
          }

          .card {
            padding: 22px;
            border-radius: 22px;
          }

          .heroBrand {
            letter-spacing: 0.03em;
          }

          .heroTagline {
            letter-spacing: 0.18em;
          }

          .statGrid {
            grid-template-columns: 1fr;
          }

          .statCardDocumentType {
            min-width: 0;
          }

          .issueHeader {
            flex-direction: column;
            align-items: flex-start;
          }

          .textMetaRow {
            flex-direction: column;
          }

          .uploadButton,
          .secondaryButton {
            width: 100%;
          }
        }
      `}</style>
    </>
  );
}