/**
 * Pre-baked analysis fixtures for the /demo page.
 * Generated by scripts/generateDemoFixtures.mjs — do not edit by hand.
 * To regenerate: node scripts/generateDemoFixtures.mjs
 */

export interface DemoIssue {
  id: string;
  label: string;
  severity: string;
  clauseReference?: string;
  message?: string;
  explanation?: string;
  recommendation?: string;
  matches?: string[];
}

export interface DemoDeadline {
  label: string;
  value: string;
  description?: string;
}

export interface DemoFixture {
  id: string;
  label: string;
  fileName: string;
  documentType: string;
  riskScore: number;
  riskLevel: string;
  summary: string;
  issues: DemoIssue[];
  deadlines: DemoDeadline[];
}

export const MARKETING_DEMO: DemoFixture = {
  id: "marketing",
  label: "Marketing Services Agreement",
  fileName: "marketing-services-agreement.txt",
  documentType: "Marketing Services Agreement",
  riskScore: 18,
  riskLevel: "high",
  summary:
    "This is a Marketing Services Agreement between Alpha Solutions LLC and BrightPath Marketing for digital marketing services at $5,000 per month. It is one of the most incomplete contracts of its type — key sections are intentionally omitted, the liability clause protects only the provider and waives your right to recover even direct losses, deliverables are entirely undefined, and critical legal sections like governing law and IP ownership are blank or missing. Do not sign this contract without significant revisions and legal review.",
  issues: [
    {
      id: "undefined-deliverables",
      label: "No defined deliverables, timelines, or performance standards",
      severity: "critical",
      clauseReference: "Section 1 – Services",
      message:
        "The contract commits you to paying $5,000 per month but leaves what you actually receive entirely undefined.",
      explanation:
        "With deliverables 'to be determined at a later date,' you have no legal basis to demand any specific work product, timeline, or quality standard. If the provider delivers minimal or subpar work, you have almost no grounds to dispute it or withhold payment. You are essentially signing a blank check.",
      recommendation:
        "Require a detailed Statement of Work (SOW) attached to this agreement before signing, specifying exactly what will be delivered, when, and how success will be measured.",
      matches: [
        "The specific deliverables, timelines, and performance metrics for these services are to be determined at a later date.",
      ],
    },
    {
      id: "direct-damages-excluded",
      label:
        "Provider cannot be held liable for any damages — including direct losses you suffer",
      severity: "critical",
      clauseReference: "Section 5 – Liability",
      message:
        "The liability clause eliminates the provider's financial responsibility for all damages, including direct ones, which is extreme and likely unenforceable in most jurisdictions.",
      explanation:
        "Normally, even contracts with liability limits allow you to recover direct losses — money you actually lost because of someone's failure. This clause tries to waive even that. If the provider runs a bad ad campaign that tanks your brand or wastes your ad budget, you could recover nothing. Courts often throw out clauses this broad, but relying on that is a gamble you should not have to take.",
      recommendation:
        "Strike the exclusion of direct damages entirely and negotiate a liability cap set at a reasonable level, such as the total fees paid in the prior 3 months.",
      matches: [
        "Provider is not liable for any damages arising from the use of services, including any direct, indirect, incidental, or consequential damages of any kind.",
      ],
    },
    {
      id: "intentionally-omitted-confidentiality",
      label: "Confidentiality section was deliberately left out",
      severity: "critical",
      clauseReference: "Section 6 – Confidentiality",
      message:
        "The confidentiality section is explicitly marked as intentionally omitted, meaning there are no enforceable protections for your business's sensitive information.",
      explanation:
        "In a marketing relationship, you will likely share customer data, marketing strategies, brand plans, and proprietary business information. With no confidentiality terms, the provider is legally free to share or use that information however they choose. The fact this was deliberately omitted — not just forgotten — is a serious red flag.",
      recommendation:
        "Demand a complete confidentiality clause that defines what counts as confidential information, how long it must be protected, and what happens if there is a breach before signing.",
      matches: [
        "Both parties agree to keep sensitive information confidential.",
        "[INTENTIONALLY OMITTED]",
      ],
    },
    {
      id: "blank-governing-law",
      label: "Governing law section is completely blank",
      severity: "critical",
      clauseReference: "Section 7 – Governing Law",
      message:
        "No state or country law is specified to govern this contract, leaving both parties without a clear legal framework if a dispute arises.",
      explanation:
        "If you ever need to enforce this contract or defend yourself in a dispute, neither side knows which state's laws apply, which court has jurisdiction, or where a case would be filed. This creates expensive uncertainty and could force you to litigate in an inconvenient location. A blank governing law clause is a drafting failure that should never appear in a signed agreement.",
      recommendation:
        "Insist that the governing law section be completed with your preferred state before signing, and confirm it includes a venue clause specifying where disputes will be heard.",
      matches: ["[left blank]"],
    },
    {
      id: "no-notice-period-termination",
      label: "Contract can be terminated instantly with no notice period",
      severity: "high",
      clauseReference: "Section 4 – Termination",
      message:
        "The termination clause allows either party to exit the agreement at any time but explicitly states no notice period is required, meaning termination could be immediate.",
      explanation:
        "If you are the client, this cuts both ways — the provider could stop all work on your campaigns with zero warning, leaving your marketing efforts exposed. If you are mid-campaign with active ad spend, this could cause real financial damage. There is also no cure period, meaning a minor dispute or misunderstanding could lead to immediate termination with no chance to fix the problem.",
      recommendation:
        "Negotiate a minimum 30-day written notice period for termination without cause, and add a 14-day cure period that allows either party to fix a breach before termination takes effect.",
      matches: [
        "Either party may terminate this agreement at any time with written notice. No notice period is specified.",
      ],
    },
    {
      id: "vague-payment-terms",
      label:
        "Payment due date is undefined and late payments carry no consequences",
      severity: "high",
      clauseReference: "Section 2 – Payment Terms",
      message:
        "Payment is due within a 'reasonable time' with no defined window, and the contract explicitly waives any late fees or interest on overdue invoices.",
      explanation:
        "If you are the provider, you have no legal tool to compel timely payment — a client could delay payment indefinitely and face no financial penalty. If you are the client, 'reasonable time' is ambiguous enough that a dispute over timing could arise unexpectedly. Either way, this clause benefits whichever party wants to delay payment.",
      recommendation:
        "Replace 'reasonable time' with a specific payment window such as Net 15 or Net 30, and add a late payment interest rate of 1.5% per month to incentivize timely payment.",
      matches: [
        "Payment is due within a reasonable time after invoicing. No late fees or interest shall apply to overdue invoices.",
      ],
    },
    {
      id: "non-functional-dispute-resolution",
      label: "Dispute resolution clause provides no actual process",
      severity: "high",
      clauseReference: "Section 8 – Dispute Resolution",
      message:
        "The dispute resolution clause says disputes will be handled 'in a mutually agreed manner,' which is not an enforceable mechanism.",
      explanation:
        "If you and the provider disagree and cannot mutually agree on how to resolve it — which is likely in any real dispute — this clause gives you nothing to fall back on. You would default to costly court litigation with no agreed rules, venue, or process. The clause is essentially a placeholder that provides no protection.",
      recommendation:
        "Replace this with a defined process — for example, mandatory mediation followed by binding arbitration in a specified city — and include a timeframe for each step.",
      matches: ["Any disputes will be handled in a mutually agreed manner."],
    },
    {
      id: "missing-0",
      label: "No IP ownership clause",
      severity: "missing",
      explanation:
        "This contract involves the creation of content, ad copy, and creative assets, but there is no clause establishing who owns that work. Without a work-for-hire designation or IP assignment, the provider may legally retain ownership of everything they create for you — meaning you could lose access to your own marketing materials if the relationship ends.",
      recommendation:
        "Add an IP ownership clause stating that all work product created under this agreement is owned by the client upon full payment, and that the provider retains no rights to it.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No data protection or privacy terms",
      severity: "missing",
      explanation:
        "Digital marketing services almost always involve handling customer data, email lists, website analytics, and potentially personal information subject to laws like GDPR or CCPA. With no data protection clause, there are no rules about how your data is stored, used, or protected — exposing you to regulatory fines and reputational damage if something goes wrong.",
      recommendation:
        "Add a data protection clause that defines each party's obligations under applicable privacy laws, restricts the provider from using your customer data for any purpose outside this agreement, and requires prompt notification of any data breach.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No indemnification clause",
      severity: "missing",
      explanation:
        "If the provider's work infringes a third-party copyright, violates advertising regulations, or causes harm to a third party, there are no indemnification terms to determine who is responsible for the resulting legal costs and claims. As the client, you could be exposed to third-party lawsuits with no contractual right to have the provider cover those costs.",
      recommendation:
        "Add a mutual indemnification clause where each party agrees to cover the other for losses caused by their own actions, with specific carve-outs for IP infringement and regulatory violations caused by the provider's work.",
      matches: [],
    },
    {
      id: "missing-3",
      label: "No warranty clause or disclaimer",
      severity: "missing",
      explanation:
        "The provider makes no representations about the quality, legality, or fitness of the services. Combined with the undefined deliverables, this means you have no contractual basis to demand competent, professional-quality work.",
      recommendation:
        "Ask for a clause where the provider warrants that services will be performed in a professional manner, comply with applicable laws, and not infringe any third-party intellectual property rights.",
      matches: [],
    },
    {
      id: "missing-4",
      label: "No audit rights",
      severity: "missing",
      explanation:
        "You are paying $5,000 per month for services with no defined deliverables and no performance metrics. Without audit rights, you have no contractual ability to review the provider's billing records, time logs, or performance data to verify you are getting what you are paying for.",
      recommendation:
        "Request a clause giving you the right to audit the provider's performance records and billing documentation with reasonable notice, no more than once per quarter.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Agreement effective date",
      value: "January 1, 2026",
      description:
        "The contract begins on this date. Given the number of critical issues identified, this agreement should not be signed in its current form — if this date is approaching, prioritize getting revisions completed urgently.",
    },
    {
      label: "Contract term end date",
      value: "December 31, 2026",
      description:
        "The agreement runs for 12 months from January 1, 2026. There is no auto-renewal clause and no renewal process defined, so both parties will need to renegotiate or let the agreement lapse at this date. Plan ahead to avoid a gap in service coverage.",
    },
    {
      label: "Payment due date",
      value: "Undefined — 'reasonable time' after invoicing",
      description:
        "There is no fixed payment deadline. This ambiguity should be resolved before signing — without a clear due date, either party can dispute what 'reasonable' means, creating unnecessary conflict each month.",
    },
  ],
};

export const NDA_DEMO: DemoFixture = {
  id: "nda",
  label: "Non-Disclosure Agreement",
  fileName: "non-disclosure-agreement.txt",
  documentType: "NDA",
  riskScore: 8,
  riskLevel: "high",
  summary:
    "This is a Non-Disclosure Agreement that claims to be 'mutual' but is entirely one-sided — only you (the Receiving Party) are bound by its rules, while Vertex Innovations Inc. faces no obligations at all. It contains multiple provisions that are either unenforceable or potentially illegal, including a ban on complying with court orders, a global non-compete, perpetual confidentiality, and a blank governing law section. Do not sign this contract without significant revisions and legal advice.",
  issues: [
    {
      id: "no-standard-carve-outs",
      label:
        "Confidential Information includes public and independently developed knowledge",
      severity: "critical",
      clauseReference: "Section 1",
      message:
        "The definition of Confidential Information explicitly excludes standard carve-outs, meaning even information you already knew or developed yourself is treated as their secret.",
      explanation:
        "If you independently invent something, learn it from a public source, or already knew it before signing, this contract still treats it as Vertex's confidential property. This could be used to claim you violated the agreement for doing ordinary business activities. Courts in most countries refuse to enforce confidentiality clauses this broad.",
      recommendation:
        "Demand that standard exclusions be added: information already in the public domain, information you independently developed, and information received from a third party without restriction.",
      matches: [
        "Information that is already publicly known, independently developed, or disclosed by a third party shall nonetheless be considered Confidential Information under this Agreement.",
        "There are no exceptions or carve-outs to this definition.",
      ],
    },
    {
      id: "legal-disclosure-prohibited",
      label:
        "You are forbidden from complying with court orders or government investigations",
      severity: "critical",
      clauseReference: "Section 3",
      message:
        "The contract prohibits you from disclosing information even when required by a court, regulator, or law enforcement, which is legally impossible to honor and could expose you to contempt of court.",
      explanation:
        "If a court subpoenas you, a regulator demands records, or a law requires disclosure, this clause tells you to refuse — but you cannot legally refuse a valid court order. Attempting to comply with this clause could result in you being found in contempt of court or violating regulatory law. The clause itself is unenforceable, but the attempt to honor it could cause you serious legal harm.",
      recommendation:
        "Require deletion of Section 3 and replacement with a standard provision allowing legally compelled disclosure with prompt prior notice to the other party where permitted.",
      matches: [
        "The Receiving Party may not disclose Confidential Information even if required by law, court order, or government authority.",
      ],
    },
    {
      id: "perpetual-confidentiality",
      label: "Confidentiality obligations last forever with no end date",
      severity: "critical",
      clauseReference: "Section 4",
      message:
        "Your confidentiality obligations never expire, which is commercially unreasonable and likely unenforceable.",
      explanation:
        "Standard NDAs limit confidentiality obligations to 2–5 years after the agreement ends. A perpetual obligation means you could be sued for a breach 20 or 30 years from now. While courts often limit enforcement of perpetual NDAs, defending against such a claim would still cost you time and money.",
      recommendation:
        "Negotiate a defined post-termination confidentiality period of 2–3 years, with trade secrets protected for longer only if specifically identified.",
      matches: [
        "The confidentiality obligations of the Receiving Party shall continue in perpetuity and shall survive the termination or expiration of this Agreement without limit.",
      ],
    },
    {
      id: "false-mutual-framing",
      label: "Agreement is labeled 'Mutual' but only binds you",
      severity: "critical",
      clauseReference: "Section 2",
      message:
        "Despite the 'Mutual NDA' title, the agreement explicitly states obligations apply only to you, not to Vertex Innovations Inc.",
      explanation:
        "You are agreeing to strict, one-sided confidentiality while Vertex can freely share, use, or disclose anything you share with them. This is a fundamental mismatch — the title creates a false impression of balance that does not exist in the actual terms. Anything you disclose to them is effectively unprotected.",
      recommendation:
        "Insist the agreement be rewritten so that identical confidentiality obligations apply to both parties symmetrically, or explicitly acknowledge you are signing a one-way NDA.",
      matches: [
        "These obligations apply only to the Receiving Party and not to the Disclosing Party.",
      ],
    },
    {
      id: "global-non-compete",
      label: "Global non-compete buried inside an NDA",
      severity: "critical",
      clauseReference: "Section 5",
      message:
        "You are being asked to agree to a worldwide restriction on working with any competitor for two years, which is almost certainly unenforceable and is an unusual and aggressive provision to include in an NDA.",
      explanation:
        "Non-compete clauses need to be geographically reasonable to be enforceable — a global ban with no industry or activity limits is routinely struck down by courts. More concerning, this type of clause typically belongs in an employment or partnership agreement where you receive significant compensation. Agreeing to it here, just in exchange for seeing some information, provides very weak legal footing for Vertex but could still cost you money to fight if they try to enforce it.",
      recommendation:
        "Refuse to sign Section 5 as written; if a non-compete is genuinely needed, negotiate narrow geographic and industry scope with clear definitions of what 'competing' means.",
      matches: [
        "the Receiving Party agrees not to directly or indirectly engage in, consult for, or have any business relationship with any company that competes with the Disclosing Party for a period of two (2) years following the termination of this Agreement. This restriction applies globally.",
      ],
    },
    {
      id: "blank-governing-law-nda",
      label: "Governing law section is intentionally left blank",
      severity: "critical",
      clauseReference: "Section 7",
      message:
        "The governing law clause contains placeholder text and has not been completed, leaving the contract without a defined legal framework.",
      explanation:
        "Without a governing law, neither party knows which country's or state's courts would hear a dispute, what laws apply, or where a lawsuit could be filed. This ambiguity could be exploited by either party or result in expensive preliminary legal battles just to determine jurisdiction before the actual dispute is even addressed.",
      recommendation:
        "Refuse to sign until Section 7 is completed with a specific governing jurisdiction and venue that is reasonable for your business location.",
      matches: ["[left blank — to be determined]"],
    },
    {
      id: "onesided-ip-assignment",
      label: "All work product you create becomes Vertex's property",
      severity: "high",
      clauseReference: "Section 6",
      message:
        "Any work product you develop that is derived from information shared under this agreement automatically belongs to Vertex, not you.",
      explanation:
        "The phrase 'work product derived therefrom' is vague enough that if you build anything after seeing Vertex's information — even something you develop independently — they could claim ownership over it. In a genuine mutual NDA, each party retains ownership of their own IP and any jointly developed work is addressed separately.",
      recommendation:
        "Negotiate clear language that each party retains ownership of its pre-existing IP and that any jointly developed work product requires a separate written agreement.",
      matches: [
        "All information shared under this Agreement and any work product derived therefrom shall remain the exclusive property of the Disclosing Party.",
      ],
    },
    {
      id: "onesided-remedies",
      label: "Only Vertex can seek emergency court relief — you cannot",
      severity: "medium",
      clauseReference: "Section 8",
      message:
        "The remedies clause gives only the Disclosing Party the right to seek injunctive relief, leaving you without equivalent legal tools if they breach the agreement.",
      explanation:
        "If Vertex misuses information you share with them, you have no corresponding right to go to court and stop them quickly. Given that the NDA is supposedly mutual in title, this one-sided remedy provision further disadvantages you and leaves your confidential information without meaningful protection.",
      recommendation:
        "Request that Section 8 be amended to give both parties equal rights to seek injunctive relief in the event of a breach.",
      matches: [
        "The Disclosing Party shall be entitled to seek injunctive relief without posting a bond.",
      ],
    },
    {
      id: "missing-0",
      label: "No termination clause",
      severity: "missing",
      explanation:
        "There is no way for either party to end this agreement, no notice requirements, and no process for returning or destroying confidential materials when the relationship ends. Combined with the perpetual confidentiality obligation, you could be bound by this contract indefinitely with no exit mechanism.",
      recommendation:
        "Ask for a termination clause that allows either party to exit with written notice (e.g., 30 days), and requires return or certified destruction of confidential materials upon termination.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No limitation of liability",
      severity: "missing",
      explanation:
        "Without a liability cap, a claimed breach — even a minor or unintentional one — could expose you to unlimited financial damages. This is especially dangerous given how broadly 'Confidential Information' is defined in this contract.",
      recommendation:
        "Negotiate a mutual cap on liability, typically set at the value of the commercial relationship or a fixed dollar amount, with carve-outs only for intentional misconduct.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No data protection provisions",
      severity: "missing",
      explanation:
        "Section 1 explicitly includes 'employee information' in the definition of Confidential Information. If personal data is shared, privacy laws like GDPR or CCPA may require specific data handling, processing, and security obligations that this contract entirely ignores — exposing you to regulatory risk.",
      recommendation:
        "Request a data protection addendum or clause that specifies how personal data will be handled, stored, and deleted in compliance with applicable privacy laws.",
      matches: [],
    },
    {
      id: "missing-3",
      label: "No dispute resolution mechanism",
      severity: "missing",
      explanation:
        "Beyond a vague reference to injunctive relief, there is no process for resolving disagreements — no arbitration, mediation, or litigation pathway. Combined with the blank governing law clause, any dispute would immediately become expensive and procedurally chaotic.",
      recommendation:
        "Add a dispute resolution clause specifying whether disputes go to arbitration or court, in which jurisdiction, and under what rules.",
      matches: [],
    },
    {
      id: "missing-4",
      label: "No warranty disclaimer",
      severity: "missing",
      explanation:
        "Without a disclaimer stating that confidential information is shared 'as-is,' you could theoretically be held responsible if information you share turns out to be inaccurate or incomplete and the other party relies on it to their detriment.",
      recommendation:
        "Request a standard clause stating that all confidential information is provided as-is, with no warranties as to accuracy, completeness, or fitness for any purpose.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Non-compete period following termination",
      value: "2 years after termination of the Agreement",
      description:
        "If signed, you would be restricted from working with any competitor of Vertex worldwide for two years after this agreement ends. Since there is no termination clause, the start of this clock is itself undefined, meaning the restriction could be interpreted as open-ended.",
    },
    {
      label: "Confidentiality obligations",
      value: "Perpetual — no end date",
      description:
        "Your confidentiality obligations begin at signing and never expire. There is no date by which you are released from these obligations, making this a permanent legal commitment.",
    },
  ],
};

export const VENDOR_DEMO: DemoFixture = {
  id: "vendor",
  label: "Vendor Supply Agreement",
  fileName: "vendor-supply-agreement.txt",
  documentType: "Vendor Agreement",
  riskScore: 12,
  riskLevel: "high",
  summary:
    "This is a Vendor Supply Agreement between SteelCore Manufacturing Ltd. and Pinnacle Retail Group, effective February 1, 2026. It is one of the most one-sided contracts a buyer can sign — you pay everything upfront with no guarantee of delivery, lose ownership of any custom products you fund, and face a large financial penalty if you try to leave. Do not sign this contract without significant renegotiation and legal review.",
  issues: [
    {
      id: "liability-cap-inadequate",
      label: "Liability cap is set at just $500",
      severity: "critical",
      clauseReference: "Section 6 - Limitation of Liability",
      message:
        "The vendor's total financial responsibility for any mistake, defect, or breach is capped at $500, no matter how large the contract or how serious the harm.",
      explanation:
        "If SteelCore ships you defective products worth $50,000, fails to deliver after you've paid in full, or causes your business significant losses, you can only recover $500. This cap covers everything — including product defects and negligence — with no exceptions. This is not a negotiating position; it is a near-total removal of your legal protection.",
      recommendation:
        "Negotiate the liability cap to reflect the actual contract value, and add carve-outs so the cap does not apply to gross negligence, willful misconduct, or product defects causing personal injury.",
      matches: [
        "Vendor's total liability under this Agreement, for any cause whatsoever and regardless of the form of action, shall not exceed five hundred dollars ($500.00).",
        "This limitation applies to all claims including those for breach of contract, negligence, and product defects.",
      ],
    },
    {
      id: "ip-ownership-buyer-adverse",
      label: "You lose ownership of custom products you pay to develop",
      severity: "critical",
      clauseReference: "Section 5 - Intellectual Property",
      message:
        "Any custom product, mold, design, or specification you fund belongs entirely to the vendor, not to you.",
      explanation:
        "If you pay SteelCore to develop a custom product or tooling designed to your specifications, they own it. They can sell that design to your competitors, and you have no right to stop them. You also have no license guaranteeing you can continue using the design if the relationship ends. You are essentially funding their product development for free.",
      recommendation:
        "Negotiate so that any custom work funded by Buyer becomes Buyer's property, or at minimum secure an exclusive, irrevocable license for the life of the commercial relationship.",
      matches: [
        "Any custom products, tooling, molds, designs, or specifications developed by Vendor for Buyer under this Agreement shall remain the exclusive intellectual property of Vendor.",
        "Buyer shall have no ownership rights in any custom work product, even if Buyer funded the development of such work.",
      ],
    },
    {
      id: "upfront-payment-no-recourse",
      label:
        "You must pay 100% upfront with no protection if goods are never delivered",
      severity: "critical",
      clauseReference: "Section 2 - Payment Terms",
      message:
        "You are required to pay the full invoice amount before any goods are shipped, and the contract provides no refund process or remedy if delivery never happens.",
      explanation:
        "You hand over all the money first, and SteelCore controls whether and when they ship. There is no defined process for getting your money back if they fail to deliver, and given the $500 liability cap in Section 6, your legal recourse for a failed delivery is essentially nothing. This creates serious cash flow and financial exposure.",
      recommendation:
        "Negotiate for milestone-based or net payment terms, and add an explicit refund obligation and delivery guarantee tied to payment.",
      matches: [
        "Buyer shall pay 100% of the invoice amount upfront prior to any shipment or delivery.",
        "Vendor reserves the right to withhold delivery until full payment is confirmed.",
      ],
    },
    {
      id: "price-increase-no-opt-out",
      label: "Vendor can raise prices 20% every year and you cannot say no",
      severity: "critical",
      clauseReference: "Section 3 - Pricing and Price Adjustments",
      message:
        "The vendor can increase prices by up to 20% annually with only 30 days' notice, and you have no right to reject or exit without paying a termination penalty.",
      explanation:
        "A 20% annual price increase compounded over a multi-year relationship can dramatically erode your margins. Because you cannot opt out of price increases without triggering the 25% termination penalty in Section 7, you are financially trapped. Simply continuing to place orders is treated as acceptance of any new pricing.",
      recommendation:
        "Cap price increases at a lower rate tied to an objective index such as CPI, and negotiate a right to terminate without penalty if increases exceed an agreed threshold.",
      matches: [
        "Vendor reserves the right to increase prices by up to twenty percent (20%) annually upon thirty (30) days written notice to Buyer.",
        "Buyer has no right to reject or opt out of price increases.",
        "Continued ordering after the notice period constitutes acceptance of the new pricing.",
      ],
    },
    {
      id: "termination-penalty-excessive",
      label: "Leaving the contract early costs you 25% of all remaining obligations",
      severity: "high",
      clauseReference: "Section 7 - Termination Penalty",
      message:
        "If you want to exit this agreement before the term ends for any reason other than the vendor's proven uncured breach, you owe a penalty equal to 25% of all remaining purchase commitments.",
      explanation:
        "If you are partway through a one-year term and need to stop — because the vendor is performing poorly, your business needs change, or you find a better supplier — you face a large financial penalty. Combined with the 20% annual price increases and the 15-day renewal window, this creates a contract that is very hard to exit without significant cost. Courts in some jurisdictions may strike down penalty clauses, but relying on litigation is expensive and uncertain.",
      recommendation:
        "Negotiate for a termination for convenience right with reasonable notice and no penalty, and clearly define 'material breach' with an explicit cure period so the exception is actually usable.",
      matches: [
        "Buyer shall pay Vendor a termination penalty equal to twenty-five percent (25%) of the total value of all remaining purchase obligations for the balance of the term.",
      ],
    },
    {
      id: "auto-renewal-short-window",
      label:
        "You have only 15 days to cancel before the contract automatically renews for another year",
      severity: "high",
      clauseReference: "Section 4 - Term and Renewal",
      message:
        "The window to cancel auto-renewal is only 15 days before the term ends, and missing it locks you into another full year with a costly exit penalty.",
      explanation:
        "Fifteen days is an extremely short window — if your team is travelling, the notice gets lost, or someone forgets to calendar the deadline, the contract renews automatically for another year. Because leaving mid-term triggers the 25% penalty in Section 7, this is not just an inconvenience — it could mean being trapped in a contract you no longer want for up to another 12 months.",
      recommendation:
        "Negotiate the auto-renewal notice window to at least 60 or 90 days, and set a calendar reminder immediately if you proceed with this agreement.",
      matches: [
        "unless either party provides written notice of cancellation no later than fifteen (15) days prior to the end of the then-current term.",
        "Failure to provide timely notice shall result in automatic renewal for an additional year.",
      ],
    },
    {
      id: "no-delivery-obligations",
      label:
        "Vendor controls all delivery schedules with no performance obligations",
      severity: "high",
      clauseReference: "Section 1 - Supply of Goods",
      message:
        "The contract explicitly states there are no delivery timelines, lead times, or performance standards, and the vendor decides when to deliver at their sole discretion.",
      explanation:
        "You could pay upfront and wait indefinitely for your goods with no contractual basis to demand timely delivery. If your business depends on receiving stock to meet customer orders or production schedules, this creates serious operational risk. There is no consequence for the vendor if they deliver late or fail to deliver in a commercially reasonable timeframe.",
      recommendation:
        "Add a defined delivery schedule or maximum lead time, and include a remedy such as refund rights or fee reductions if delivery timelines are not met.",
      matches: [
        "No delivery timelines, lead times, or performance standards are defined in this Agreement.",
        "Vendor shall determine delivery schedules at its sole discretion.",
      ],
    },
    {
      id: "dispute-resolution-placeholder",
      label:
        "The dispute resolution clause is a blank placeholder with no actual process",
      severity: "medium",
      clauseReference: "Section 8 - Dispute Resolution",
      message:
        "Section 8 contains placeholder text that defers any dispute resolution process to a future agreement between the parties, providing no real mechanism for resolving disagreements.",
      explanation:
        "If a dispute arises — over a failed delivery, defective goods, or a billing error — there is no agreed process for resolving it. This means any disagreement defaults to expensive, time-consuming litigation with no prior agreed steps like mediation or escalation. Given the number of one-sided clauses in this contract, disputes are a realistic prospect.",
      recommendation:
        "Replace the placeholder with a real dispute resolution clause specifying escalation to senior management, followed by mediation, and then litigation or arbitration in a mutually agreed venue.",
      matches: [
        "[No dispute resolution process defined. All disputes shall be handled as agreed upon by the parties at the time of the dispute.]",
      ],
    },
    {
      id: "missing-0",
      label: "No product warranties of any kind",
      severity: "missing",
      explanation:
        "The vendor makes no promises about the quality, fitness, or conformity of the goods they supply. If products arrive defective, fail to meet specifications, or are unfit for their intended purpose, you have no warranty to enforce — and the $500 liability cap means your legal remedy is essentially worthless.",
      recommendation:
        "Require explicit warranties of merchantability, fitness for purpose, and conformance to agreed specifications, with a defined warranty period and a clear remedy such as replacement, repair, or refund.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No indemnification protections",
      severity: "missing",
      explanation:
        "There is no clause requiring the vendor to protect you from third-party claims arising from their products — such as a customer injured by a defective product, or an IP infringement claim because the vendor used someone else's design. You could face lawsuits for problems entirely caused by SteelCore.",
      recommendation:
        "Add a mutual indemnification clause requiring each party to cover the other for claims arising from their own negligence, misconduct, or IP infringement.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No confidentiality or non-disclosure obligations",
      severity: "missing",
      explanation:
        "You may need to share custom product designs, pricing strategies, customer requirements, or business plans with the vendor to receive the goods you need. Without a confidentiality clause, SteelCore has no legal obligation to keep any of that information secret and can share or use it freely.",
      recommendation:
        "Add a mutual confidentiality clause covering all business information shared during the relationship, with obligations surviving termination for at least two to three years.",
      matches: [],
    },
    {
      id: "missing-3",
      label: "No defined product specifications or deliverables",
      severity: "missing",
      explanation:
        "The contract references a pricing exhibit but does not define what goods are actually being supplied, to what quality standard, or by what acceptance criteria. Without this, there is no contractual basis to reject non-conforming goods or enforce any standard of quality.",
      recommendation:
        "Attach a detailed product specification schedule as an exhibit defining the goods, quality standards, inspection rights, and acceptance criteria before signing.",
      matches: [],
    },
    {
      id: "missing-4",
      label: "No vendor insurance requirements",
      severity: "missing",
      explanation:
        "SteelCore supplies physical goods that could cause property damage or personal injury. There is no requirement for them to carry product liability insurance, general liability coverage, or any other insurance. If something goes wrong, they may be unable to cover the losses — and with a $500 liability cap, you cannot recover from them anyway.",
      recommendation:
        "Require the vendor to maintain adequate product liability and general liability insurance at specified minimum coverage levels and provide certificates of insurance annually.",
      matches: [],
    },
    {
      id: "missing-5",
      label: "No dispute resolution mechanism",
      severity: "missing",
      explanation:
        "The existing Section 8 is a non-functional placeholder. Without an agreed process, any disagreement goes straight to litigation — the most expensive and time-consuming option available.",
      recommendation:
        "Include a tiered dispute resolution process: first senior management escalation, then mediation, then binding arbitration or litigation in a specified, mutually convenient venue.",
      matches: [],
    },
    {
      id: "missing-6",
      label: "No audit rights",
      severity: "missing",
      explanation:
        "Given the vendor has unilateral rights to raise prices by 20% annually and you have no way to verify invoices or pricing calculations, you need the ability to audit relevant records. Without audit rights, you are entirely dependent on SteelCore's self-reported numbers.",
      recommendation:
        "Negotiate a right to audit the vendor's pricing, production, and compliance records on reasonable notice, particularly given the unilateral price adjustment rights.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Contract effective date",
      value: "February 1, 2026",
      description:
        "The agreement commences on this date. Ensure all negotiations, amendments, and signatures are completed before this date, as obligations begin immediately.",
    },
    {
      label: "Auto-renewal cancellation deadline (Year 1)",
      value: "January 17, 2027",
      description:
        "You must deliver written notice of cancellation no later than 15 days before the January 31, 2027 end of the first term. Missing this deadline automatically locks you into another full year from February 1, 2027, with a 25% termination penalty if you then try to exit mid-term.",
    },
    {
      label: "Price increase notice period",
      value: "30 days written notice",
      description:
        "The vendor may raise prices by up to 20% at any time with 30 days' notice. You have no right to reject increases, so continuing to order after the 30-day window constitutes acceptance. Monitor all notices carefully as each increase compounds over time.",
    },
  ],
};

export const FREELANCE_DEMO: DemoFixture = {
  id: "freelance",
  label: "Freelance Contract",
  fileName: "freelance-contract.txt",
  documentType: "Independent Contractor Agreement",
  riskScore: 11,
  riskLevel: "high",
  summary:
    "This is a Freelance Services Agreement between Nova Digital LLC and an independent contractor for web development and design work. It is one of the most one-sided contractor agreements possible — it strips you of your pre-existing tools and code, exposes you to unlimited financial liability, lets the client demand free work indefinitely, and could block you from working in your industry for three years. Do not sign this contract without significant renegotiation and legal review.",
  issues: [
    {
      id: "ip-preexisting-assignment",
      label: "Your personal tools, code, and frameworks get handed over to the client",
      severity: "critical",
      clauseReference: "Section 3 — Intellectual Property — Work for Hire",
      message:
        "The IP clause purports to transfer ownership of tools, frameworks, and libraries you built before this engagement — not just work created for this client.",
      explanation:
        "If you sign this, Nova Digital LLC could claim ownership of your personal code libraries, reusable components, open-source tools you authored, and any frameworks you bring to the job. This means you could be legally prevented from using your own pre-existing work on future projects. This provision likely cannot be fully enforced, but fighting it in court is expensive and disruptive.",
      recommendation:
        "Negotiate to limit the IP assignment strictly to deliverables created solely for this engagement, and add a clause explicitly retaining your ownership of all pre-existing tools with a license granted to the client for use in the deliverables only.",
      matches: [
        "This assignment includes all pre-existing tools, frameworks, libraries, and methodologies used by Freelancer in the performance of services, including any open-source or proprietary tools developed prior to this engagement.",
        "Freelancer waives all moral rights in the work product.",
      ],
    },
    {
      id: "unlimited-indemnification",
      label: "You are on the hook for unlimited legal costs with no ceiling",
      severity: "critical",
      clauseReference: "Section 7 — Legal Compliance Costs",
      message:
        "You must cover all of the client's legal costs, fines, and settlements arising from compliance failures, with no cap, no carve-out for the client's own fault, and no reciprocal protection for you.",
      explanation:
        "If a third party sues Nova Digital because of something in your deliverables — even if the client gave you bad instructions — you could be responsible for paying their entire legal bill, no matter how large. There is no dollar limit, no shared responsibility, and the client faces zero consequences for contributing to the problem. A single lawsuit could financially ruin you.",
      recommendation:
        "Insist on a mutual indemnification clause, add a carve-out excluding the client's own negligence or misconduct, and cap total indemnification liability at the total fees paid under the agreement.",
      matches: [
        "Freelancer shall indemnify and reimburse Client for all such costs without limitation.",
      ],
    },
    {
      id: "no-liability-cap",
      label: "There is no limit on how much money you could owe the client",
      severity: "critical",
      clauseReference: "Agreement-wide — No Limitation of Liability clause present",
      message:
        "The contract contains no clause capping either party's financial exposure, which combined with the unlimited indemnification creates theoretically boundless personal financial risk for you.",
      explanation:
        "Without a liability cap, any claim against you — whether for a missed deadline, a compliance issue, or a disputed deliverable — has no financial ceiling. Standard contracts cap liability at the total fees paid. This contract has no such protection, meaning a dispute over a small project could expose you to losses that dwarf what you were ever paid.",
      recommendation:
        "Add a mutual limitation of liability clause capping each party's total exposure at the total fees paid to you under the agreement, and exclude consequential, indirect, and punitive damages.",
      matches: [
        "Freelancer shall indemnify and reimburse Client for all such costs without limitation.",
      ],
    },
    {
      id: "overbroad-non-compete",
      label:
        "A 3-year ban on working in your industry disguised as a non-solicitation clause",
      severity: "critical",
      clauseReference: "Section 6 — Non-Solicitation",
      message:
        "Despite being labeled 'Non-Solicitation,' this clause is actually a sweeping non-compete that could bar you from freelancing, consulting, or being employed anywhere in any market Nova Digital operates in for three years after the engagement ends.",
      explanation:
        "If Nova Digital operates in the web development, digital marketing, or e-commerce space, this clause could effectively prevent you from doing your job for three years — for any client, anywhere. This type of broad non-compete is banned or unenforceable in many states including California, Minnesota, and others. Even where it might be enforceable, it would need to be challenged in court at your expense.",
      recommendation:
        "Strike this clause entirely or replace it with a narrowly scoped, time-limited non-solicitation covering only direct clients you worked with during this engagement, with a maximum 12-month duration.",
      matches: [
        "Freelancer shall not provide services to, consult for, or be employed by any person or entity that competes with Client's business in any market in which Client operates, directly or indirectly.",
        "for a period of three (3) years following termination",
      ],
    },
    {
      id: "unfair-payment-terms",
      label:
        "You could wait 90 days to get paid — or longer — with no penalty to the client",
      severity: "high",
      clauseReference: "Section 4 — Payment; Section 5 — Kill Fee",
      message:
        "Payment is due 90 days after invoicing, there are no late fees for overdue payments, and the client can dispute any invoice to restart the 90-day clock indefinitely.",
      explanation:
        "Industry standard for freelancers is Net-15 to Net-30. At Net-90, you could finish a project in March and not get paid until June — with no interest accruing if they miss that too. Worse, the client can dispute any invoice at any time to reset the clock, creating a legal mechanism for indefinite payment delays. If the client cancels mid-project, you get paid only for hours the client agrees to 'accept,' giving them full subjective control over what they owe you.",
      recommendation:
        "Negotiate payment to Net-15 or Net-30, add a late payment interest clause (1.5% per month is standard), define a clear invoice dispute process with a deadline, and include a kill fee of at least 25–50% of the remaining project value.",
      matches: [
        "Client shall pay Freelancer within ninety (90) days of invoice submission.",
        "No interest or late fees shall accrue on overdue payments.",
        "Client reserves the right to dispute any invoice within the 90-day period, which shall restart the payment clock upon resolution.",
        "no cancellation fee or kill fee shall be payable to Freelancer",
      ],
    },
    {
      id: "unlimited-free-revisions",
      label:
        "The client can demand unlimited free revisions forever, including after the project is done",
      severity: "high",
      clauseReference: "Section 2 — Revisions and Scope; Section 1 — Services",
      message:
        "The scope of work is undefined and can be changed at any time by the client, and you are obligated to make unlimited free revisions of any nature at any point, even after final delivery.",
      explanation:
        "This means there is no finish line. A client could accept your final deliverable and then request months of additional changes for free. Combined with verbally communicated deadlines and scope that can be changed at any time, you have no legal protection against being asked to work indefinitely without additional pay. 'Final delivery' effectively means nothing under this contract.",
      recommendation:
        "Define the scope of work in a written statement of work attached as an exhibit, limit revision rounds (e.g., two rounds of revisions per deliverable), specify that post-delivery changes constitute a new billable scope, and require all scope changes to be in writing.",
      matches: [
        "Client may request unlimited revisions to any deliverable at any time, including after final delivery.",
        "Freelancer agrees to complete all requested revisions at no additional charge regardless of the nature or volume of changes requested.",
        "The scope of work, deliverables, and deadlines shall be communicated by Client via email or verbal instruction and may be modified by Client at any time.",
      ],
    },
    {
      id: "one-sided-venue",
      label:
        "Any dispute must be fought in a court in Fairbanks, Alaska — at your expense",
      severity: "high",
      clauseReference: "Section 8 — Jurisdiction and Governing Law",
      message:
        "You have waived your right to object to being sued or having to sue in Fairbanks, Alaska, regardless of where you actually live or work.",
      explanation:
        "If a dispute arises, you would be required to hire an Alaska-licensed attorney and potentially travel to Fairbanks to appear in court. For most freelancers located outside Alaska, this makes pursuing a claim or defending yourself financially impractical, effectively discouraging you from enforcing your rights even if you are in the right.",
      recommendation:
        "Negotiate for disputes to be handled in your home jurisdiction, or propose binding arbitration administered by a neutral body such as the American Arbitration Association, which allows remote participation.",
      matches: [
        "any disputes shall be resolved exclusively in the state or federal courts located in Fairbanks, Alaska.",
        "Freelancer waives any objection to personal jurisdiction or venue in such courts.",
      ],
    },
    {
      id: "missing-0",
      label: "No confidentiality or non-disclosure obligations",
      severity: "missing",
      explanation:
        "As a web developer, you will likely access the client's proprietary systems, source code, customer data, and business information. Without an NDA, there is nothing legally preventing either party from disclosing the other's sensitive information. This also creates compliance risk if you encounter personal data subject to privacy laws.",
      recommendation:
        "Add a mutual confidentiality clause requiring both parties to keep the other's proprietary information confidential for a defined period (typically 2–3 years), with standard exceptions for publicly available information.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No termination clause",
      severity: "missing",
      explanation:
        "The contract has no defined end date, no notice period, and no process for either party to exit the agreement. This creates legal ambiguity about when your obligations end and leaves you potentially bound indefinitely. Section 5 references cancellation but does not function as a proper termination provision.",
      recommendation:
        "Add a termination clause allowing either party to end the agreement with written notice (14–30 days is standard), specifying payment for work completed through the termination date, and defining which obligations survive termination.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No data protection or privacy obligations",
      severity: "missing",
      explanation:
        "Web development work often involves handling personal data, user accounts, or systems subject to GDPR, CCPA, or other privacy regulations. The complete absence of any data handling terms means neither party's responsibilities are defined, creating regulatory exposure that could result in fines or liability for both you and the client.",
      recommendation:
        "Add a data protection clause specifying how personal data must be handled, who is responsible for compliance with applicable privacy laws, breach notification obligations, and data deletion requirements at the end of the engagement.",
      matches: [],
    },
    {
      id: "missing-3",
      label: "No warranty disclaimer",
      severity: "missing",
      explanation:
        "Without a warranty disclaimer, implied warranties of fitness for a particular purpose or merchantability may apply under law, potentially exposing you to claims that your deliverables did not meet unstated expectations. Given the vague scope of this agreement, this risk is amplified.",
      recommendation:
        "Add a clause specifying that deliverables are provided 'as is' after acceptance, disclaim implied warranties, and define an explicit acceptance period during which the client may request corrections.",
      matches: [],
    },
    {
      id: "missing-4",
      label: "No audit rights for hour verification",
      severity: "missing",
      explanation:
        "You are paid for 'hours worked and accepted by Client,' but there is no defined process for tracking, reporting, or verifying hours. Without audit rights or a time-tracking requirement, disputes about billable hours have no objective basis for resolution.",
      recommendation:
        "Add a clause requiring you to maintain time records in a specified format and granting the client a right to request records within a defined window, while also giving you the right to document and substantiate hours billed.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Agreement effective date",
      value: "March 1, 2026",
      description:
        "The agreement becomes binding on this date. All obligations, including the non-compete, IP assignment, and unlimited revision requirements, take effect immediately on signing.",
    },
    {
      label: "Client payment window after invoice",
      value: "90 days from invoice submission",
      description:
        "The client has 90 days to pay each invoice. If they raise a dispute at any point within that window, the clock resets from zero upon resolution, meaning payment could be delayed well beyond 90 days with no penalty to the client.",
    },
    {
      label: "Non-compete restriction period after termination",
      value: "3 years following termination",
      description:
        "Once the agreement ends — even if terminated tomorrow — you are contractually barred from providing services to any entity competing with Nova Digital in any market they operate in for three full years. Missing or underestimating this restriction could result in breach of contract claims against you.",
    },
  ],
};

export const DEMO_FIXTURES: DemoFixture[] = [
  MARKETING_DEMO,
  NDA_DEMO,
  VENDOR_DEMO,
  FREELANCE_DEMO,
];
