/**
 * Pre-baked analysis fixtures for the /demo page.
 * Generated by scripts/generateDemoFixtures.mjs — do not edit by hand.
 * To regenerate: node scripts/generateDemoFixtures.mjs
 */

export interface DemoIssue {
  id: string;
  label: string;
  severity: string;
  clauseReference?: string;
  message?: string;
  explanation?: string;
  recommendation?: string;
  matches?: string[];
}

export interface DemoDeadline {
  label: string;
  value: string;
  description?: string;
}

export interface DemoFixture {
  id: string;
  label: string;
  fileName: string;
  documentType: string;
  riskScore: number;
  riskLevel: string;
  summary: string;
  issues: DemoIssue[];
  deadlines: DemoDeadline[];
}

export const MARKETING_DEMO: DemoFixture = {
  id: "marketing",
  label: "Marketing Services Agreement",
  fileName: "marketing-services-agreement.txt",
  documentType: "Marketing Services Agreement",
  riskScore: 68,
  riskLevel: "medium",
  summary:
    "This is a Marketing Services Agreement between Alpha Solutions LLC (Provider) and BrightPath Marketing (Client) for digital marketing services starting January 1, 2026. The contract is reasonably well-structured with clear deliverables, mutual liability protections, and IP ownership in your favor, but it has a few meaningful gaps — most notably no audit rights over ad spend, a vague data breach notification timeline, and an automatic renewal clause that could lock you in for another full year if you miss a 30-day window. It warrants attention before signing but is not unusually dangerous.",
  issues: [
    {
      id: "auto-renewal-short-window",
      label: "Auto-Renewal With Only 30-Day Opt-Out Window",
      severity: "medium",
      clauseReference: "Section 3 — Term",
      message:
        "The contract automatically renews for a full year unless you cancel at least 30 days before the end of the current term, leaving very little time to act.",
      explanation:
        "If you miss the 30-day notice window by even one day, you are committed to another 12 months and $60,000 in fees. A 30-day window on a 12-month contract is a tight margin, and the contract contains no fee renegotiation right at renewal, meaning you could be locked in at the same rate regardless of performance or market changes.",
      recommendation:
        "Negotiate the non-renewal notice window to at least 60–90 days and add a right to renegotiate fees before each renewal term.",
      matches: [
        "this Agreement shall renew for successive one-year terms unless either party provides written notice of non-renewal at least thirty (30) days before the end of the then-current term",
      ],
    },
    {
      id: "narrow-indemnification-scope",
      label: "Indemnification Only Covers Extreme Misconduct, Not Ordinary Mistakes",
      severity: "medium",
      clauseReference: "Section 10 — Indemnification",
      message:
        "The indemnification clause only protects you if the Provider commits gross negligence or willful misconduct, meaning you bear the cost of any harm caused by ordinary negligence or professional errors.",
      explanation:
        "If the Provider makes a careless mistake — for example, publishing inaccurate content that damages your brand or mismanaging ad budgets — you cannot seek indemnification unless you can prove they acted with extreme recklessness or intent. Ordinary professional errors, which are far more common, are excluded. This means you could incur real losses and be left paying your own legal and recovery costs.",
      recommendation:
        "Expand the indemnification scope to include claims arising from the Provider's general negligence and material breach of contract, not just gross negligence or willful misconduct.",
      matches: [
        "arising from the Indemnifying Party's: (a) gross negligence or willful misconduct; or (b) infringement of a third party's intellectual property rights",
      ],
    },
    {
      id: "liability-cap-low",
      label: "Liability Cap Limited to Just 3 Months of Fees",
      severity: "medium",
      clauseReference: "Section 6 — Liability",
      message:
        "The maximum amount either party can recover from the other is capped at only the last 3 months of fees paid, which is $15,000 — potentially far less than the actual harm a serious failure could cause.",
      explanation:
        "If the Provider mismanages a large paid ad campaign, destroys your SEO rankings, or causes a data breach, your ability to recover damages is capped at $15,000 regardless of actual losses. For a business spending on paid advertising and relying on this provider for its digital presence, real-world losses from a serious failure could easily exceed that amount.",
      recommendation:
        "Negotiate a higher liability cap — at minimum 12 months of fees ($60,000) — and ensure data breaches and confidentiality violations are carved out from the cap entirely.",
      matches: [
        "Each party's total cumulative liability to the other under or in connection with this Agreement shall not exceed the total fees paid by Client in the three (3) months immediately preceding the event giving rise to the claim",
      ],
    },
    {
      id: "vague-breach-notification",
      label: "No Timeline for Data Breach Notification",
      severity: "medium",
      clauseReference: "Section 8 — Data Protection",
      message:
        "The contract requires the Provider to 'promptly' notify you of a data breach but sets no specific timeframe, which could leave you exposed to regulatory penalties if you are subject to GDPR's 72-hour reporting rule.",
      explanation:
        "Under GDPR, you may be required to report a breach to regulators within 72 hours of becoming aware of it. If your Provider notifies you on day 4 citing 'prompt' notice, you have already missed your legal deadline and could face significant fines. The word 'promptly' is legally vague and unenforceable as a hard deadline.",
      recommendation:
        "Replace 'promptly' with a specific contractual deadline — such as 'within 48 hours of discovery' — to ensure you have time to meet your own regulatory obligations.",
      matches: [
        "Provider shall promptly notify Client of any actual or suspected unauthorized access to Client data",
      ],
    },
    {
      id: "outcome-based-seo-obligation",
      label: "SEO Ranking Obligation Is Outcome-Based and May Be Unenforceable",
      severity: "low",
      clauseReference: "Section 1 — Services and Deliverables",
      message:
        "The Provider is contractually obligated to 'maintain or improve' your organic search rankings, but search rankings are controlled by third parties (Google, Bing) and can shift for reasons entirely outside the Provider's control.",
      explanation:
        "If a search engine algorithm update drops your rankings, the Provider could technically be in breach of contract despite performing all their work correctly. Conversely, the vagueness of this obligation could also make it difficult for you to hold the Provider accountable if their work genuinely causes a ranking decline, since they may argue external factors were responsible.",
      recommendation:
        "Clarify that the ranking obligation is subject to a best-efforts or industry-standard-practices qualifier and define a clear process for determining whether underperformance is attributable to the Provider.",
      matches: [
        "Provider shall maintain or improve Client's organic search ranking for agreed target keywords",
      ],
    },
    {
      id: "no-deliverable-acceptance-process",
      label: "No Acceptance or Rejection Process for Deliverables",
      severity: "low",
      clauseReference: "Section 1 — Services and Deliverables",
      message:
        "The contract specifies what will be delivered each month but contains no process for you to review, accept, request revisions, or reject deliverables.",
      explanation:
        "Without an acceptance process, there is no clear point at which a deliverable is deemed complete and approved — or rejected due to quality issues. This creates ambiguity about when payment is owed, how many revisions you are entitled to, and what happens if you are dissatisfied with a blog post, social media asset, or campaign report.",
      recommendation:
        "Add a written acceptance process specifying a review period (e.g., 5 business days), a defined number of revision rounds, and a clear outcome if no response is given within the review window.",
      matches: [
        "Provider agrees to deliver the following digital marketing services each calendar month",
      ],
    },
    {
      id: "missing-0",
      label: "No Audit Rights Over Ad Spend and Performance Data",
      severity: "missing",
      explanation:
        "The Provider is managing your paid search and social ad campaigns, which means they control how your advertising budget is spent. Without a contractual right to audit the Provider's records, you have no independent way to verify that reported ad spend, impressions, clicks, and conversions are accurate. This is a significant financial blind spot, especially as the monthly fee grows or ad budgets increase.",
      recommendation:
        "Request an audit rights clause giving you the right to inspect the Provider's performance records, ad account data, and spend reports — at your cost — no more than once per year with reasonable notice.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No Insurance Requirements",
      severity: "missing",
      explanation:
        "The contract does not require the Provider to carry any insurance — such as professional liability (errors and omissions), cyber liability, or general liability coverage. If the Provider causes a data breach, publishes infringing content, or makes a costly advertising error, there may be no insurance policy available to pay for resulting losses, even if the Provider is technically liable.",
      recommendation:
        "Require the Provider to maintain at minimum professional liability (E&O) and cyber liability insurance with specified minimum coverage amounts, and to provide a certificate of insurance upon request.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No Non-Solicitation Clause",
      severity: "missing",
      explanation:
        "Neither party is restricted from recruiting or hiring the other's employees or contractors during or after the agreement. If the Provider's key team members working on your account are valuable and you want to hire them directly — or if the Provider tries to recruit your marketing staff — there is nothing in this contract preventing it.",
      recommendation:
        "Add a mutual non-solicitation clause prohibiting either party from directly recruiting or hiring the other's employees or contractors during the agreement term and for 12 months after termination.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Contract Start Date",
      value: "January 1, 2026",
      description:
        "The agreement becomes effective and services begin on this date. Ensure both parties have signed before this date to avoid disputes about whether the contract is in force.",
    },
    {
      label: "Initial Term End Date",
      value: "December 31, 2026",
      description:
        "The 12-month initial term ends on this date. If you do not wish to renew, you must send written non-renewal notice before this date.",
    },
    {
      label: "Non-Renewal Notice Deadline (Year 1)",
      value: "December 1, 2026",
      description:
        "You must provide written notice of non-renewal at least 30 days before the end of the initial term. Missing this deadline automatically locks you into another 12-month term worth $60,000 in fees. Calendar this well in advance.",
    },
    {
      label: "Monthly Invoice Payment Due",
      value: "Net-30 from invoice date",
      description:
        "Each monthly invoice must be paid within 30 days of issue. After 45 days unpaid, the Provider may suspend services with 10 days' written notice. Late invoices also accrue interest at 1.5% per month (18% annually) from the due date.",
    },
    {
      label: "Monthly Ad Performance Summary Deadline",
      value: "Within 5 business days of month-end",
      description:
        "The Provider is contractually required to deliver a written ad campaign performance summary within 5 business days after each month closes. Track this monthly to ensure the Provider is meeting their delivery obligations.",
    },
    {
      label: "Termination for Convenience Notice Period",
      value: "30 days written notice",
      description:
        "Either party can end the agreement at any time by giving 30 days' written notice. You will owe payment for all services rendered through the termination date, so account for one final month of fees.",
    },
    {
      label: "Breach Cure Period",
      value: "14 days from written notice",
      description:
        "If either party breaches the contract, the breaching party has 14 days to fix the problem after receiving written notice. If the breach is not cured within 14 days, the non-breaching party may terminate immediately. Send breach notices in writing and track this window carefully.",
    },
    {
      label: "Confidentiality Obligations Post-Termination",
      value: "2 years after termination",
      description:
        "Both parties must keep each other's confidential information secret for 2 years after the contract ends. Ensure your team is aware of this ongoing obligation when offboarding from this relationship.",
    },
    {
      label: "Annual Deliverable Scope Review",
      value: "At least once per year",
      description:
        "The contract requires both parties to review and update the deliverable scope in writing at least annually. Use this opportunity to renegotiate fees, adjust service levels, or address performance issues before renewal.",
    },
  ],
};

export const NDA_DEMO: DemoFixture = {
  id: "nda",
  label: "Non-Disclosure Agreement",
  fileName: "non-disclosure-agreement.txt",
  documentType: "NDA",
  riskScore: 8,
  riskLevel: "high",
  summary:
    "This is a Non-Disclosure Agreement that claims to be 'mutual' but is entirely one-sided — only you (the Receiving Party) are bound by its rules, while Vertex Innovations Inc. faces no obligations at all. It contains multiple provisions that are either unenforceable or potentially illegal, including a ban on complying with court orders, a global non-compete, perpetual confidentiality, and a blank governing law section. Do not sign this contract without significant revisions and legal advice.",
  issues: [
    {
      id: "no-standard-carve-outs",
      label:
        "Confidential Information includes public and independently developed knowledge",
      severity: "critical",
      clauseReference: "Section 1",
      message:
        "The definition of Confidential Information explicitly excludes standard carve-outs, meaning even information you already knew or developed yourself is treated as their secret.",
      explanation:
        "If you independently invent something, learn it from a public source, or already knew it before signing, this contract still treats it as Vertex's confidential property. This could be used to claim you violated the agreement for doing ordinary business activities. Courts in most countries refuse to enforce confidentiality clauses this broad.",
      recommendation:
        "Demand that standard exclusions be added: information already in the public domain, information you independently developed, and information received from a third party without restriction.",
      matches: [
        "Information that is already publicly known, independently developed, or disclosed by a third party shall nonetheless be considered Confidential Information under this Agreement.",
        "There are no exceptions or carve-outs to this definition.",
      ],
    },
    {
      id: "legal-disclosure-prohibited",
      label:
        "You are forbidden from complying with court orders or government investigations",
      severity: "critical",
      clauseReference: "Section 3",
      message:
        "The contract prohibits you from disclosing information even when required by a court, regulator, or law enforcement, which is legally impossible to honor and could expose you to contempt of court.",
      explanation:
        "If a court subpoenas you, a regulator demands records, or a law requires disclosure, this clause tells you to refuse — but you cannot legally refuse a valid court order. Attempting to comply with this clause could result in you being found in contempt of court or violating regulatory law. The clause itself is unenforceable, but the attempt to honor it could cause you serious legal harm.",
      recommendation:
        "Require deletion of Section 3 and replacement with a standard provision allowing legally compelled disclosure with prompt prior notice to the other party where permitted.",
      matches: [
        "The Receiving Party may not disclose Confidential Information even if required by law, court order, or government authority.",
      ],
    },
    {
      id: "perpetual-confidentiality",
      label: "Confidentiality obligations last forever with no end date",
      severity: "critical",
      clauseReference: "Section 4",
      message:
        "Your confidentiality obligations never expire, which is commercially unreasonable and likely unenforceable.",
      explanation:
        "Standard NDAs limit confidentiality obligations to 2–5 years after the agreement ends. A perpetual obligation means you could be sued for a breach 20 or 30 years from now. While courts often limit enforcement of perpetual NDAs, defending against such a claim would still cost you time and money.",
      recommendation:
        "Negotiate a defined post-termination confidentiality period of 2–3 years, with trade secrets protected for longer only if specifically identified.",
      matches: [
        "The confidentiality obligations of the Receiving Party shall continue in perpetuity and shall survive the termination or expiration of this Agreement without limit.",
      ],
    },
    {
      id: "false-mutual-framing",
      label: "Agreement is labeled 'Mutual' but only binds you",
      severity: "critical",
      clauseReference: "Section 2",
      message:
        "Despite the 'Mutual NDA' title, the agreement explicitly states obligations apply only to you, not to Vertex Innovations Inc.",
      explanation:
        "You are agreeing to strict, one-sided confidentiality while Vertex can freely share, use, or disclose anything you share with them. This is a fundamental mismatch — the title creates a false impression of balance that does not exist in the actual terms. Anything you disclose to them is effectively unprotected.",
      recommendation:
        "Insist the agreement be rewritten so that identical confidentiality obligations apply to both parties symmetrically, or explicitly acknowledge you are signing a one-way NDA.",
      matches: [
        "These obligations apply only to the Receiving Party and not to the Disclosing Party.",
      ],
    },
    {
      id: "global-non-compete",
      label: "Global non-compete buried inside an NDA",
      severity: "critical",
      clauseReference: "Section 5",
      message:
        "You are being asked to agree to a worldwide restriction on working with any competitor for two years, which is almost certainly unenforceable and is an unusual and aggressive provision to include in an NDA.",
      explanation:
        "Non-compete clauses need to be geographically reasonable to be enforceable — a global ban with no industry or activity limits is routinely struck down by courts. More concerning, this type of clause typically belongs in an employment or partnership agreement where you receive significant compensation. Agreeing to it here, just in exchange for seeing some information, provides very weak legal footing for Vertex but could still cost you money to fight if they try to enforce it.",
      recommendation:
        "Refuse to sign Section 5 as written; if a non-compete is genuinely needed, negotiate narrow geographic and industry scope with clear definitions of what 'competing' means.",
      matches: [
        "the Receiving Party agrees not to directly or indirectly engage in, consult for, or have any business relationship with any company that competes with the Disclosing Party for a period of two (2) years following the termination of this Agreement. This restriction applies globally.",
      ],
    },
    {
      id: "blank-governing-law-nda",
      label: "Governing law section is intentionally left blank",
      severity: "critical",
      clauseReference: "Section 7",
      message:
        "The governing law clause contains placeholder text and has not been completed, leaving the contract without a defined legal framework.",
      explanation:
        "Without a governing law, neither party knows which country's or state's courts would hear a dispute, what laws apply, or where a lawsuit could be filed. This ambiguity could be exploited by either party or result in expensive preliminary legal battles just to determine jurisdiction before the actual dispute is even addressed.",
      recommendation:
        "Refuse to sign until Section 7 is completed with a specific governing jurisdiction and venue that is reasonable for your business location.",
      matches: ["[left blank — to be determined]"],
    },
    {
      id: "onesided-ip-assignment",
      label: "All work product you create becomes Vertex's property",
      severity: "high",
      clauseReference: "Section 6",
      message:
        "Any work product you develop that is derived from information shared under this agreement automatically belongs to Vertex, not you.",
      explanation:
        "The phrase 'work product derived therefrom' is vague enough that if you build anything after seeing Vertex's information — even something you develop independently — they could claim ownership over it. In a genuine mutual NDA, each party retains ownership of their own IP and any jointly developed work is addressed separately.",
      recommendation:
        "Negotiate clear language that each party retains ownership of its pre-existing IP and that any jointly developed work product requires a separate written agreement.",
      matches: [
        "All information shared under this Agreement and any work product derived therefrom shall remain the exclusive property of the Disclosing Party.",
      ],
    },
    {
      id: "onesided-remedies",
      label: "Only Vertex can seek emergency court relief — you cannot",
      severity: "medium",
      clauseReference: "Section 8",
      message:
        "The remedies clause gives only the Disclosing Party the right to seek injunctive relief, leaving you without equivalent legal tools if they breach the agreement.",
      explanation:
        "If Vertex misuses information you share with them, you have no corresponding right to go to court and stop them quickly. Given that the NDA is supposedly mutual in title, this one-sided remedy provision further disadvantages you and leaves your confidential information without meaningful protection.",
      recommendation:
        "Request that Section 8 be amended to give both parties equal rights to seek injunctive relief in the event of a breach.",
      matches: [
        "The Disclosing Party shall be entitled to seek injunctive relief without posting a bond.",
      ],
    },
    {
      id: "missing-0",
      label: "No termination clause",
      severity: "missing",
      explanation:
        "There is no way for either party to end this agreement, no notice requirements, and no process for returning or destroying confidential materials when the relationship ends. Combined with the perpetual confidentiality obligation, you could be bound by this contract indefinitely with no exit mechanism.",
      recommendation:
        "Ask for a termination clause that allows either party to exit with written notice (e.g., 30 days), and requires return or certified destruction of confidential materials upon termination.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No limitation of liability",
      severity: "missing",
      explanation:
        "Without a liability cap, a claimed breach — even a minor or unintentional one — could expose you to unlimited financial damages. This is especially dangerous given how broadly 'Confidential Information' is defined in this contract.",
      recommendation:
        "Negotiate a mutual cap on liability, typically set at the value of the commercial relationship or a fixed dollar amount, with carve-outs only for intentional misconduct.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No data protection provisions",
      severity: "missing",
      explanation:
        "Section 1 explicitly includes 'employee information' in the definition of Confidential Information. If personal data is shared, privacy laws like GDPR or CCPA may require specific data handling, processing, and security obligations that this contract entirely ignores — exposing you to regulatory risk.",
      recommendation:
        "Request a data protection addendum or clause that specifies how personal data will be handled, stored, and deleted in compliance with applicable privacy laws.",
      matches: [],
    },
    {
      id: "missing-3",
      label: "No dispute resolution mechanism",
      severity: "missing",
      explanation:
        "Beyond a vague reference to injunctive relief, there is no process for resolving disagreements — no arbitration, mediation, or litigation pathway. Combined with the blank governing law clause, any dispute would immediately become expensive and procedurally chaotic.",
      recommendation:
        "Add a dispute resolution clause specifying whether disputes go to arbitration or court, in which jurisdiction, and under what rules.",
      matches: [],
    },
    {
      id: "missing-4",
      label: "No warranty disclaimer",
      severity: "missing",
      explanation:
        "Without a disclaimer stating that confidential information is shared 'as-is,' you could theoretically be held responsible if information you share turns out to be inaccurate or incomplete and the other party relies on it to their detriment.",
      recommendation:
        "Request a standard clause stating that all confidential information is provided as-is, with no warranties as to accuracy, completeness, or fitness for any purpose.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Non-compete period following termination",
      value: "2 years after termination of the Agreement",
      description:
        "If signed, you would be restricted from working with any competitor of Vertex worldwide for two years after this agreement ends. Since there is no termination clause, the start of this clock is itself undefined, meaning the restriction could be interpreted as open-ended.",
    },
    {
      label: "Confidentiality obligations",
      value: "Perpetual — no end date",
      description:
        "Your confidentiality obligations begin at signing and never expire. There is no date by which you are released from these obligations, making this a permanent legal commitment.",
    },
  ],
};

export const VENDOR_DEMO: DemoFixture = {
  id: "vendor",
  label: "Vendor Supply Agreement",
  fileName: "vendor-supply-agreement.txt",
  documentType: "Vendor Agreement",
  riskScore: 74,
  riskLevel: "medium",
  summary:
    "This is a Vendor Supply Agreement between SteelCore Manufacturing (supplier) and Pinnacle Retail Group (buyer) for recurring goods purchases over a one-year auto-renewing term. The contract is reasonably balanced with good protections on liability, IP, and warranties, but a few terms around auto-renewal notice timing, arbitration location, and warranty remedy limits deserve attention before signing. Overall this is a moderate-risk contract — manageable with a few targeted adjustments.",
  issues: [
    {
      id: "auto-renewal-90-day-notice",
      label: "Auto-Renewal Requires 90-Day Opt-Out Notice",
      severity: "medium",
      clauseReference: "Section 4 — Term and Renewal",
      message:
        "The contract auto-renews each year unless you give 90 days' notice of non-renewal, which is an unusually long window to track.",
      explanation:
        "If you miss the 90-day window before the anniversary date, you are locked in for another full year with no way out except a 90-day convenience termination — meaning you could end up 6+ months into an unwanted contract year before it ends. Most vendor agreements use a 30–60 day window, making 90 days more burdensome for the Buyer.",
      recommendation:
        "Negotiate to reduce the auto-renewal opt-out notice period to 30 or 60 days, and set a calendar reminder for the opt-out deadline each year.",
      matches: [
        "automatically renew for successive one-year terms unless either party provides written notice of non-renewal at least ninety (90) days before the end of the then-current term",
      ],
    },
    {
      id: "arbitration-delaware-jurisdiction",
      label: "Arbitration Fixed in Wilmington, Delaware",
      severity: "medium",
      clauseReference: "Section 11 — Dispute Resolution",
      message:
        "All binding arbitration must take place in Wilmington, Delaware, regardless of where your business is located.",
      explanation:
        "If a dispute escalates to arbitration, your team would need to travel to Delaware or hire local Delaware counsel, adding cost and inconvenience. This is particularly burdensome if Pinnacle Retail Group is headquartered far from Delaware. In a dispute over a modest invoice amount, travel costs alone could outweigh the claim.",
      recommendation:
        "Negotiate to allow arbitration to be conducted remotely or in a mutually agreed location closer to your principal place of business.",
      matches: [
        "binding arbitration under the rules of the American Arbitration Association in Wilmington, Delaware",
      ],
    },
    {
      id: "warranty-sole-remedy",
      label: "Warranty Remedies Are Limited to Repair, Replace, or Credit Only",
      severity: "medium",
      clauseReference: "Section 7 — Product Warranties",
      message:
        "If goods are defective, your only remedies are repair, replacement, or a purchase price credit — you cannot claim broader damages even if the defect causes downstream losses.",
      explanation:
        "Suppose defective goods cause you to miss a major retail season, lose a customer contract, or incur extra labor costs. Under this clause, you can only get the cost of the faulty goods back — not your lost profits or consequential losses. For a retail business where product availability is critical, this gap could be costly.",
      recommendation:
        "Request that the sole-remedy limitation be removed or at minimum carve out situations involving widespread defects, recall events, or defects that cause customer-facing harm.",
      matches: [
        "repair or replace the defective goods or issue a credit for the purchase price, as Buyer's sole and exclusive remedy for warranty claims",
      ],
    },
    {
      id: "vendor-shipment-withhold-right",
      label: "Vendor Can Withhold Shipments for Overdue Invoices",
      severity: "low",
      clauseReference: "Section 2 — Payment Terms",
      message:
        "The Vendor can stop all future shipments if any single invoice is more than 60 days overdue, after only 10 days' warning.",
      explanation:
        "If there is a billing dispute or an administrative payment delay on one invoice, the Vendor could halt your entire supply chain with just 10 days' notice. For a retail business dependent on steady inventory, even a short supply interruption could affect customer commitments. The provision doesn't distinguish between disputed and undisputed invoices.",
      recommendation:
        "Request that shipment withholding rights apply only to undisputed overdue invoices, and that the cure period be extended to at least 15–20 days.",
      matches: [
        "Vendor may withhold future shipments after providing 10 days' written notice if any invoice remains unpaid for more than 60 days",
      ],
    },
    {
      id: "liability-cap-12-month-lookback",
      label: "Liability Cap Based on Prior 12 Months of Payments",
      severity: "low",
      clauseReference: "Section 6 — Limitation of Liability",
      message:
        "The maximum either party can recover in a dispute is capped at what Buyer paid the Vendor in the prior 12 months.",
      explanation:
        "This cap works in your favor when you are the claimant (you can recover up to a full year of payments), but it also limits your exposure as Buyer if the Vendor sues you. The carve-outs for gross negligence, willful misconduct, and payment obligations are reasonable and standard. Overall this provision is balanced, but worth understanding going in.",
      recommendation:
        "Confirm the 12-month cap is acceptable given your expected annual spend with this Vendor, and verify the gross negligence and indemnification carve-outs are retained as written.",
      matches: [
        "total cumulative liability to the other under or in connection with this Agreement shall not exceed the total amounts paid or payable by Buyer to Vendor in the twelve (12) months immediately preceding the event giving rise to the claim",
      ],
    },
    {
      id: "missing-0",
      label: "No Force Majeure Clause",
      severity: "missing",
      explanation:
        "There is no provision addressing what happens if either party cannot perform due to events outside their control — such as natural disasters, pandemics, supply chain disruptions, or government actions. Without this, a party could be held in breach for failing to deliver or pay when performance was genuinely impossible. This is particularly relevant for a manufacturing supply relationship where logistics delays are a real risk.",
      recommendation:
        "Request a standard force majeure clause that excuses non-performance caused by events outside a party's reasonable control, with a defined notice obligation and a right to terminate if the disruption lasts beyond 60–90 days.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No Product Recall or Safety Defect Procedure",
      severity: "missing",
      explanation:
        "For a retail business selling physical goods to consumers, there is no provision addressing what happens if supplied goods need to be recalled due to a safety defect. Without clear obligations on who manages recalls, who bears the cost, and what Vendor's obligations are, Pinnacle Retail Group could face significant unrecovered costs and reputational damage in a recall scenario.",
      recommendation:
        "Request a clause requiring Vendor to promptly notify Buyer of any known safety defects, to cooperate in any recall, and to bear recall-related costs for defects originating from Vendor's manufacturing.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No Audit Rights for Pricing or Compliance",
      severity: "missing",
      explanation:
        "Buyer has no right to audit Vendor's pricing, invoices, or compliance with the agreement's terms. In a long-term recurring supply relationship, this means Buyer cannot independently verify that it is being charged correctly per Exhibit A or that pricing adjustments are applied as agreed.",
      recommendation:
        "Request a right to audit Vendor's invoicing records and pricing calculations on reasonable notice, no more than once per year, at Buyer's expense.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Auto-Renewal Opt-Out Deadline (Year 1)",
      value: "November 3, 2026 (90 days before February 1, 2027)",
      description:
        "If you do not want this agreement to automatically renew for a second year, you must send written notice of non-renewal by approximately November 3, 2026. Missing this date locks you in for another full year.",
    },
    {
      label: "Agreement Start Date",
      value: "February 1, 2026",
      description:
        "The agreement is effective from this date, meaning supply obligations, payment terms, and all other provisions are live from this point.",
    },
    {
      label: "Initial Term End Date",
      value: "January 31, 2027",
      description:
        "The one-year initial term ends on this date, after which the agreement automatically rolls over unless notice has been given 90 days prior.",
    },
    {
      label: "Termination for Convenience Notice Period",
      value: "90 days written notice",
      description:
        "Either party can exit the agreement at any time by giving 90 days' written notice. Buyer remains responsible for payment on all orders already confirmed before the termination date takes effect.",
    },
    {
      label: "Price Increase Opt-Out Window",
      value: "30 days from receipt of price increase notice",
      description:
        "If Vendor proposes a price increase, you have 30 days to respond with a termination notice to exit without penalty. Missing this window means you accept the new pricing.",
    },
    {
      label: "Overdue Invoice Cure Period Before Shipment Hold",
      value: "10 days written notice after 60 days overdue",
      description:
        "If an invoice goes 60 days unpaid, Vendor can halt all shipments with just 10 days' notice. Monitor invoice aging closely to avoid supply disruption.",
    },
    {
      label: "Product Warranty Period",
      value: "12 months from delivery date",
      description:
        "Defect claims must be raised within 12 months of delivery. Claims submitted after this window will not be covered under the warranty provisions.",
    },
    {
      label: "Confidentiality Survival Period",
      value: "2 years after termination",
      description:
        "Both parties' confidentiality obligations continue for two years after the agreement ends, meaning sensitive information shared during the relationship remains protected post-contract.",
    },
  ],
};

export const FREELANCE_DEMO: DemoFixture = {
  id: "freelance",
  label: "Freelance Contract",
  fileName: "freelance-contract.txt",
  documentType: "Independent Contractor Agreement",
  riskScore: 11,
  riskLevel: "high",
  summary:
    "This is a Freelance Services Agreement between Nova Digital LLC and an independent contractor for web development and design work. It is one of the most one-sided contractor agreements possible — it strips you of your pre-existing tools and code, exposes you to unlimited financial liability, lets the client demand free work indefinitely, and could block you from working in your industry for three years. Do not sign this contract without significant renegotiation and legal review.",
  issues: [
    {
      id: "ip-preexisting-assignment",
      label: "Your personal tools, code, and frameworks get handed over to the client",
      severity: "critical",
      clauseReference: "Section 3 — Intellectual Property — Work for Hire",
      message:
        "The IP clause purports to transfer ownership of tools, frameworks, and libraries you built before this engagement — not just work created for this client.",
      explanation:
        "If you sign this, Nova Digital LLC could claim ownership of your personal code libraries, reusable components, open-source tools you authored, and any frameworks you bring to the job. This means you could be legally prevented from using your own pre-existing work on future projects. This provision likely cannot be fully enforced, but fighting it in court is expensive and disruptive.",
      recommendation:
        "Negotiate to limit the IP assignment strictly to deliverables created solely for this engagement, and add a clause explicitly retaining your ownership of all pre-existing tools with a license granted to the client for use in the deliverables only.",
      matches: [
        "This assignment includes all pre-existing tools, frameworks, libraries, and methodologies used by Freelancer in the performance of services, including any open-source or proprietary tools developed prior to this engagement.",
        "Freelancer waives all moral rights in the work product.",
      ],
    },
    {
      id: "unlimited-indemnification",
      label: "You are on the hook for unlimited legal costs with no ceiling",
      severity: "critical",
      clauseReference: "Section 7 — Legal Compliance Costs",
      message:
        "You must cover all of the client's legal costs, fines, and settlements arising from compliance failures, with no cap, no carve-out for the client's own fault, and no reciprocal protection for you.",
      explanation:
        "If a third party sues Nova Digital because of something in your deliverables — even if the client gave you bad instructions — you could be responsible for paying their entire legal bill, no matter how large. There is no dollar limit, no shared responsibility, and the client faces zero consequences for contributing to the problem. A single lawsuit could financially ruin you.",
      recommendation:
        "Insist on a mutual indemnification clause, add a carve-out excluding the client's own negligence or misconduct, and cap total indemnification liability at the total fees paid under the agreement.",
      matches: [
        "Freelancer shall indemnify and reimburse Client for all such costs without limitation.",
      ],
    },
    {
      id: "no-liability-cap",
      label: "There is no limit on how much money you could owe the client",
      severity: "critical",
      clauseReference: "Agreement-wide — No Limitation of Liability clause present",
      message:
        "The contract contains no clause capping either party's financial exposure, which combined with the unlimited indemnification creates theoretically boundless personal financial risk for you.",
      explanation:
        "Without a liability cap, any claim against you — whether for a missed deadline, a compliance issue, or a disputed deliverable — has no financial ceiling. Standard contracts cap liability at the total fees paid. This contract has no such protection, meaning a dispute over a small project could expose you to losses that dwarf what you were ever paid.",
      recommendation:
        "Add a mutual limitation of liability clause capping each party's total exposure at the total fees paid to you under the agreement, and exclude consequential, indirect, and punitive damages.",
      matches: [
        "Freelancer shall indemnify and reimburse Client for all such costs without limitation.",
      ],
    },
    {
      id: "overbroad-non-compete",
      label:
        "A 3-year ban on working in your industry disguised as a non-solicitation clause",
      severity: "critical",
      clauseReference: "Section 6 — Non-Solicitation",
      message:
        "Despite being labeled 'Non-Solicitation,' this clause is actually a sweeping non-compete that could bar you from freelancing, consulting, or being employed anywhere in any market Nova Digital operates in for three years after the engagement ends.",
      explanation:
        "If Nova Digital operates in the web development, digital marketing, or e-commerce space, this clause could effectively prevent you from doing your job for three years — for any client, anywhere. This type of broad non-compete is banned or unenforceable in many states including California, Minnesota, and others. Even where it might be enforceable, it would need to be challenged in court at your expense.",
      recommendation:
        "Strike this clause entirely or replace it with a narrowly scoped, time-limited non-solicitation covering only direct clients you worked with during this engagement, with a maximum 12-month duration.",
      matches: [
        "Freelancer shall not provide services to, consult for, or be employed by any person or entity that competes with Client's business in any market in which Client operates, directly or indirectly.",
        "for a period of three (3) years following termination",
      ],
    },
    {
      id: "unfair-payment-terms",
      label:
        "You could wait 90 days to get paid — or longer — with no penalty to the client",
      severity: "high",
      clauseReference: "Section 4 — Payment; Section 5 — Kill Fee",
      message:
        "Payment is due 90 days after invoicing, there are no late fees for overdue payments, and the client can dispute any invoice to restart the 90-day clock indefinitely.",
      explanation:
        "Industry standard for freelancers is Net-15 to Net-30. At Net-90, you could finish a project in March and not get paid until June — with no interest accruing if they miss that too. Worse, the client can dispute any invoice at any time to reset the clock, creating a legal mechanism for indefinite payment delays. If the client cancels mid-project, you get paid only for hours the client agrees to 'accept,' giving them full subjective control over what they owe you.",
      recommendation:
        "Negotiate payment to Net-15 or Net-30, add a late payment interest clause (1.5% per month is standard), define a clear invoice dispute process with a deadline, and include a kill fee of at least 25–50% of the remaining project value.",
      matches: [
        "Client shall pay Freelancer within ninety (90) days of invoice submission.",
        "No interest or late fees shall accrue on overdue payments.",
        "Client reserves the right to dispute any invoice within the 90-day period, which shall restart the payment clock upon resolution.",
        "no cancellation fee or kill fee shall be payable to Freelancer",
      ],
    },
    {
      id: "unlimited-free-revisions",
      label:
        "The client can demand unlimited free revisions forever, including after the project is done",
      severity: "high",
      clauseReference: "Section 2 — Revisions and Scope; Section 1 — Services",
      message:
        "The scope of work is undefined and can be changed at any time by the client, and you are obligated to make unlimited free revisions of any nature at any point, even after final delivery.",
      explanation:
        "This means there is no finish line. A client could accept your final deliverable and then request months of additional changes for free. Combined with verbally communicated deadlines and scope that can be changed at any time, you have no legal protection against being asked to work indefinitely without additional pay. 'Final delivery' effectively means nothing under this contract.",
      recommendation:
        "Define the scope of work in a written statement of work attached as an exhibit, limit revision rounds (e.g., two rounds of revisions per deliverable), specify that post-delivery changes constitute a new billable scope, and require all scope changes to be in writing.",
      matches: [
        "Client may request unlimited revisions to any deliverable at any time, including after final delivery.",
        "Freelancer agrees to complete all requested revisions at no additional charge regardless of the nature or volume of changes requested.",
        "The scope of work, deliverables, and deadlines shall be communicated by Client via email or verbal instruction and may be modified by Client at any time.",
      ],
    },
    {
      id: "one-sided-venue",
      label:
        "Any dispute must be fought in a court in Fairbanks, Alaska — at your expense",
      severity: "high",
      clauseReference: "Section 8 — Jurisdiction and Governing Law",
      message:
        "You have waived your right to object to being sued or having to sue in Fairbanks, Alaska, regardless of where you actually live or work.",
      explanation:
        "If a dispute arises, you would be required to hire an Alaska-licensed attorney and potentially travel to Fairbanks to appear in court. For most freelancers located outside Alaska, this makes pursuing a claim or defending yourself financially impractical, effectively discouraging you from enforcing your rights even if you are in the right.",
      recommendation:
        "Negotiate for disputes to be handled in your home jurisdiction, or propose binding arbitration administered by a neutral body such as the American Arbitration Association, which allows remote participation.",
      matches: [
        "any disputes shall be resolved exclusively in the state or federal courts located in Fairbanks, Alaska.",
        "Freelancer waives any objection to personal jurisdiction or venue in such courts.",
      ],
    },
    {
      id: "missing-0",
      label: "No confidentiality or non-disclosure obligations",
      severity: "missing",
      explanation:
        "As a web developer, you will likely access the client's proprietary systems, source code, customer data, and business information. Without an NDA, there is nothing legally preventing either party from disclosing the other's sensitive information. This also creates compliance risk if you encounter personal data subject to privacy laws.",
      recommendation:
        "Add a mutual confidentiality clause requiring both parties to keep the other's proprietary information confidential for a defined period (typically 2–3 years), with standard exceptions for publicly available information.",
      matches: [],
    },
    {
      id: "missing-1",
      label: "No termination clause",
      severity: "missing",
      explanation:
        "The contract has no defined end date, no notice period, and no process for either party to exit the agreement. This creates legal ambiguity about when your obligations end and leaves you potentially bound indefinitely. Section 5 references cancellation but does not function as a proper termination provision.",
      recommendation:
        "Add a termination clause allowing either party to end the agreement with written notice (14–30 days is standard), specifying payment for work completed through the termination date, and defining which obligations survive termination.",
      matches: [],
    },
    {
      id: "missing-2",
      label: "No data protection or privacy obligations",
      severity: "missing",
      explanation:
        "Web development work often involves handling personal data, user accounts, or systems subject to GDPR, CCPA, or other privacy regulations. The complete absence of any data handling terms means neither party's responsibilities are defined, creating regulatory exposure that could result in fines or liability for both you and the client.",
      recommendation:
        "Add a data protection clause specifying how personal data must be handled, who is responsible for compliance with applicable privacy laws, breach notification obligations, and data deletion requirements at the end of the engagement.",
      matches: [],
    },
    {
      id: "missing-3",
      label: "No warranty disclaimer",
      severity: "missing",
      explanation:
        "Without a warranty disclaimer, implied warranties of fitness for a particular purpose or merchantability may apply under law, potentially exposing you to claims that your deliverables did not meet unstated expectations. Given the vague scope of this agreement, this risk is amplified.",
      recommendation:
        "Add a clause specifying that deliverables are provided 'as is' after acceptance, disclaim implied warranties, and define an explicit acceptance period during which the client may request corrections.",
      matches: [],
    },
    {
      id: "missing-4",
      label: "No audit rights for hour verification",
      severity: "missing",
      explanation:
        "You are paid for 'hours worked and accepted by Client,' but there is no defined process for tracking, reporting, or verifying hours. Without audit rights or a time-tracking requirement, disputes about billable hours have no objective basis for resolution.",
      recommendation:
        "Add a clause requiring you to maintain time records in a specified format and granting the client a right to request records within a defined window, while also giving you the right to document and substantiate hours billed.",
      matches: [],
    },
  ],
  deadlines: [
    {
      label: "Agreement effective date",
      value: "March 1, 2026",
      description:
        "The agreement becomes binding on this date. All obligations, including the non-compete, IP assignment, and unlimited revision requirements, take effect immediately on signing.",
    },
    {
      label: "Client payment window after invoice",
      value: "90 days from invoice submission",
      description:
        "The client has 90 days to pay each invoice. If they raise a dispute at any point within that window, the clock resets from zero upon resolution, meaning payment could be delayed well beyond 90 days with no penalty to the client.",
    },
    {
      label: "Non-compete restriction period after termination",
      value: "3 years following termination",
      description:
        "Once the agreement ends — even if terminated tomorrow — you are contractually barred from providing services to any entity competing with Nova Digital in any market they operate in for three full years. Missing or underestimating this restriction could result in breach of contract claims against you.",
    },
  ],
};

export const DEMO_FIXTURES: DemoFixture[] = [
  MARKETING_DEMO,
  NDA_DEMO,
  VENDOR_DEMO,
  FREELANCE_DEMO,
];
